// GENERATED by `slab gen wc` — do not edit.

/** Join one `each` item into a full canonical scene key.
 * `itemKey(each, item)` addresses the item root; `itemKey(each, item, rel)`
 * appends a template-relative key. `item` is escaped per the canonical
 * scene-key grammar (`%` → `%25`, `/` → `%2F`, `~` → `%7E`). */
export declare function itemKey(each: string, item: string | number, rel?: string): string;

/** Metadata captured for every emitted signal. */
export interface SignalMeta {
   readonly x: number;
   readonly y: number;
   readonly dx: number;
   readonly dy: number;
   readonly drag_dx: number;
   readonly drag_dy: number;
   readonly mods: number;
   readonly button: number;
   readonly clicks: number;
   readonly key: string;
   readonly src_key: string;
   readonly src_item: string;
   readonly cancelled: boolean;
   readonly dropped: boolean;
   /** Deepest hit-target canonical key on pointer-derived signals. */
   readonly hit_key?: string;
   /** Pressed key name on keyboard-driven activation. */
   readonly pressed_key?: string;
}
/** Detail carried by non-text signal CustomEvents. */
export interface SignalDetail {
   readonly item: string;
   readonly meta: SignalMeta;
}
/** Detail carried by Change, Submit, and Resize CustomEvents. */
export interface TextSignalDetail extends SignalDetail {
   readonly text: string;
}

/** One layout or runtime diagnostic from the current frame. */
export interface FrameDiagnostic {
   readonly code: string;
   readonly line: number;
   readonly msg: string;
}
/** Inspectable current-frame data exposed by `lastFrame`. */
export interface SlabFrame {
   readonly width: number;
   readonly height: number;
   readonly dirty: boolean;
   readonly motionActive: boolean;
   readonly diagnostics: readonly FrameDiagnostic[];
}
/** Detail carried by the `slab-diagnostics` CustomEvent. */
export interface SlabDiagnosticsDetail {
   readonly diagnostics: readonly FrameDiagnostic[];
}

/** One retained scene entry returned by `sceneSnapshot()`. */
export interface SceneNode {
   key: string;
   node: number;
   parent: number;
   kind: number;
   x: number;
   y: number;
   w: number;
   h: number;
   radius: number;
   rotation: number;
   cx: number;
   cy: number;
   flags: number;
   content_main: number;
   scroll_off: number;
   is_row: boolean;
   scroll: boolean;
   src_line: number;
   scroll_cross: number;
   content_cross: number;
   role: string;
   label: string;
   desc: string;
   checked: boolean | 'mixed' | null;
   expanded: boolean | null;
   selected: boolean | null;
   active_descendant: string;
   controls: string;
   value_now: number | null;
   value_min: number | null;
   value_max: number | null;
   value_text: string;
   modal: boolean | null;
   live: 'off' | 'polite' | 'assertive' | null;
   live_atomic: boolean | null;
   level: number | null;
   pos_in_set: number | null;
   set_size: number | null;
   disabled: boolean;
   focused: boolean;
   /** Whether the node carries an ACTIVE `field=` binder this frame. */
   editable: boolean;
   /** Painted subtree text in scene order, lines joined with `\n`. */
   text: string;
}

export interface RootItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "leaf"?: boolean;
   "horizontal"?: boolean;
   "show_mdb"?: boolean;
   "show_store"?: boolean;
   "tabs"?: RootTabsItem[];
   "children"?: RootItem[];
}

export interface RootTabsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "name"?: string;
   "note"?: string;
   "tint"?: string | number;
   "badge"?: string;
   "active"?: boolean;
   "hot"?: boolean;
}

export interface TabsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "name"?: string;
   "note"?: string;
   "tint"?: string | number;
   "badge"?: string;
   "active"?: boolean;
   "hot"?: boolean;
}

export interface ChildrenItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "leaf"?: boolean;
   "horizontal"?: boolean;
   "show_mdb"?: boolean;
   "show_store"?: boolean;
   "tabs"?: ChildrenTabsItem[];
   "children"?: ChildrenItem[];
}

export interface ChildrenTabsItem {
   /** Stable per-item identity; defaults to the array index. */
   key?: string | number;
   "name"?: string;
   "note"?: string;
   "tint"?: string | number;
   "badge"?: string;
   "active"?: boolean;
   "hot"?: boolean;
}

/** Canonical full scene keys for authored `#id` nodes. */
export declare const SlabVscodeElementKeys: {
   readonly "sidebar": "col@0/row@1/#sidebar";
   readonly "sashL": "col@0/row@1/#sashL";
   readonly "center": "col@0/row@1/#center";
   readonly "grid": "col@0/row@1/#center/#grid";
   readonly "egroups": "col@0/row@1/#center/#grid/#egroups";
   readonly "sashP": "col@0/row@1/#center/#sashP";
   readonly "panel": "col@0/row@1/#center/#panel";
   readonly "sashR": "col@0/row@1/#sashR";
   readonly "chat": "col@0/row@1/#chat";
};
export type SlabVscodeElementSceneKey = (typeof SlabVscodeElementKeys)[keyof typeof SlabVscodeElementKeys];

/** Template-relative scene keys per `each` list; join with `itemKey`. */
export declare const SlabVscodeElementItemKeys: {
   readonly "egroups": {
      readonly each: "col@0/row@1/#center/#grid/#egroups";
      readonly item: {
         readonly "panes": "stack@0/#panes";
         readonly "kids": "stack@0/#panes/#kids";
         readonly "chrome": "stack@0/#chrome";
         readonly "strip": "stack@0/#chrome/#strip";
         readonly "tabs": "stack@0/#chrome/#strip/#tabs";
         readonly "crumb": "stack@0/#chrome/#crumb";
         readonly "ed": "stack@0/#chrome/#ed";
         readonly "content": "stack@0/#chrome/#ed/#content";
         readonly "zone": "stack@0/#chrome/#ed/#zone";
      };
   };
   readonly "kids": {
      readonly each: "stack@0/#panes/#kids";
      readonly item: {
      };
   };
   readonly "tabs": {
      readonly each: "stack@0/#chrome/#strip/#tabs";
      readonly item: {
         readonly "body": "col@0/stack@0/#body";
         readonly "indl": "col@0/stack@0/#indl";
         readonly "indr": "col@0/stack@0/#indr";
      };
   };
};

export declare class SlabVscodeElement extends HTMLElement {
   /** Expose scene geometry on globalThis.__slabDebug for tests. */
   static debug: boolean;
   /** Current compiler-declared theme; empty means authored values. */
   get theme(): string;
   set theme(v: string);
   setTheme(name: string): boolean;
   getTheme(): string;
   /** Read one resolved token for the active theme. */
   getToken(path: string): string | number | undefined;
   /** Move focus to a keyed node; an empty key clears focus. */
   setFocus(key: string, visible?: boolean): boolean;
   /** Clear kernel focus and its visible focus ring. */
   clearFocus(): boolean;
   /** Reveal, materialize, and focus one virtual-list item. */
   focusItem(each: string, index: number): boolean;
   /** Explain the most recent failed focus request. */
   focusNote(): string;
   /** Return the focused scene key, or null when focus is clear. */
   focusedKey(): string | null;
   /** Report whether the focused node is an editable field. */
   inEditField(): boolean;
   /** Most recently painted frame, including complete diagnostics. */
   readonly lastFrame: SlabFrame | null;
   /** Cumulative per-instance diagnostics since the document mounted. */
   readonly diagnostics: readonly FrameDiagnostic[];
   addEventListener(type: 'slab-diagnostics', listener: (event: CustomEvent<SlabDiagnosticsDetail>) => void, options?: boolean | AddEventListenerOptions): void;
   /** Replace a keyed field buffer and reset its edit history. */
   setFieldText(key: string, text: string): boolean;
   /** Read a keyed field's committed text. */
   fieldText(key: string): string | undefined;
   /** Set a keyed scroll offset on axis 0 (main) or 1 (cross). */
   setScroll(key: string, axis: number, off: number): boolean;
   /** Read a keyed scroll offset on axis 0 (main) or 1 (cross). */
   getScroll(key: string, axis: number): number;
   /** Register or replace a named runtime image. */
   imgRegister(name: string, width: number, height: number, format: number, bytes: Uint8Array): number;
   /** Unregister a named runtime image. */
   imgUnregister(name: string): boolean;
   /** Read runtime or embedded image metadata by unified index. */
   imgInfo(image: number): readonly [width: number, height: number, format: number, generation: number] | null;
   /** Read runtime or embedded image bytes by unified index. */
   imgBytes(image: number): Uint8Array;
   /** Scroll ancestors minimally to reveal a keyed node. */
   reveal(key: string, margin: number): boolean;
   /** Reveal one virtual-list item using the requested alignment. */
   revealItem(each: string, index: number, align: number): boolean;
   /** Read a virtual list's materialized half-open item window. */
   eachWindow(each: string): readonly [start: number, end: number];
   /** Set the extent overlay controlled by a keyed divider. */
   setDivider(key: string, extent: number): boolean;
   /** Read a keyed divider's extent overlay. */
   getDivider(key: string): number;
   /** Set one retained split-pane size. */
   setSplit(paneKey: string, size: number): boolean;
   /** Read one retained split-pane size. */
   getSplit(paneKey: string): number;
   /** Set one host app state (selected, disabled, custom idents) on a keyed node. */
   setNodeState(key: string, name: string, on: boolean): boolean;
   /** Return the current retained scene, stable until the next solve. */
   sceneSnapshot(): readonly SceneNode[];
   get 'root'(): RootItem[];
   set 'root'(v: RootItem[]);
   /** Set one scalar parameter by name. */
   setParam(name: string, v: unknown): boolean;
   /** Resolve after the next retained solve and painted frame. */
   whenSettled(): Promise<void>;
   /** Read the last scalar parameter value accepted by this element. */
   getParam(name: string): unknown;
   /** Replace a root or nested list at its runtime path. */
   setList(name: string, path: string, v: unknown): boolean;
   /** Read the last root or nested list accepted at its runtime path. */
   getList(name: string, path: string): unknown;
}

/** Canonical full scene keys for authored `#id` nodes. */
export declare const SlabEditorTabElementKeys: {
   readonly "body": "EditorTab@0/col@0/stack@0/#body";
   readonly "indl": "EditorTab@0/col@0/stack@0/#indl";
   readonly "indr": "EditorTab@0/col@0/stack@0/#indr";
};
export type SlabEditorTabElementSceneKey = (typeof SlabEditorTabElementKeys)[keyof typeof SlabEditorTabElementKeys];

/** Template-relative scene keys per `each` list; join with `itemKey`. */
export declare const SlabEditorTabElementItemKeys: {
};

export declare class SlabEditorTabElement extends HTMLElement {
   /** Expose scene geometry on globalThis.__slabDebug for tests. */
   static debug: boolean;
   /** Current compiler-declared theme; empty means authored values. */
   get theme(): string;
   set theme(v: string);
   setTheme(name: string): boolean;
   getTheme(): string;
   /** Read one resolved token for the active theme. */
   getToken(path: string): string | number | undefined;
   /** Move focus to a keyed node; an empty key clears focus. */
   setFocus(key: string, visible?: boolean): boolean;
   /** Clear kernel focus and its visible focus ring. */
   clearFocus(): boolean;
   /** Reveal, materialize, and focus one virtual-list item. */
   focusItem(each: string, index: number): boolean;
   /** Explain the most recent failed focus request. */
   focusNote(): string;
   /** Return the focused scene key, or null when focus is clear. */
   focusedKey(): string | null;
   /** Report whether the focused node is an editable field. */
   inEditField(): boolean;
   /** Most recently painted frame, including complete diagnostics. */
   readonly lastFrame: SlabFrame | null;
   /** Cumulative per-instance diagnostics since the document mounted. */
   readonly diagnostics: readonly FrameDiagnostic[];
   addEventListener(type: 'slab-diagnostics', listener: (event: CustomEvent<SlabDiagnosticsDetail>) => void, options?: boolean | AddEventListenerOptions): void;
   /** Replace a keyed field buffer and reset its edit history. */
   setFieldText(key: string, text: string): boolean;
   /** Read a keyed field's committed text. */
   fieldText(key: string): string | undefined;
   /** Set a keyed scroll offset on axis 0 (main) or 1 (cross). */
   setScroll(key: string, axis: number, off: number): boolean;
   /** Read a keyed scroll offset on axis 0 (main) or 1 (cross). */
   getScroll(key: string, axis: number): number;
   /** Register or replace a named runtime image. */
   imgRegister(name: string, width: number, height: number, format: number, bytes: Uint8Array): number;
   /** Unregister a named runtime image. */
   imgUnregister(name: string): boolean;
   /** Read runtime or embedded image metadata by unified index. */
   imgInfo(image: number): readonly [width: number, height: number, format: number, generation: number] | null;
   /** Read runtime or embedded image bytes by unified index. */
   imgBytes(image: number): Uint8Array;
   /** Scroll ancestors minimally to reveal a keyed node. */
   reveal(key: string, margin: number): boolean;
   /** Reveal one virtual-list item using the requested alignment. */
   revealItem(each: string, index: number, align: number): boolean;
   /** Read a virtual list's materialized half-open item window. */
   eachWindow(each: string): readonly [start: number, end: number];
   /** Set the extent overlay controlled by a keyed divider. */
   setDivider(key: string, extent: number): boolean;
   /** Read a keyed divider's extent overlay. */
   getDivider(key: string): number;
   /** Set one retained split-pane size. */
   setSplit(paneKey: string, size: number): boolean;
   /** Read one retained split-pane size. */
   getSplit(paneKey: string): number;
   /** Set one host app state (selected, disabled, custom idents) on a keyed node. */
   setNodeState(key: string, name: string, on: boolean): boolean;
   /** Return the current retained scene, stable until the next solve. */
   sceneSnapshot(): readonly SceneNode[];
   get 'name'(): string | undefined;
   set 'name'(v: string);
   get 'note'(): string | undefined;
   set 'note'(v: string);
   get 'tint'(): string | number | undefined;
   set 'tint'(v: string | number);
   get 'badge'(): string | undefined;
   set 'badge'(v: string);
   get 'active'(): boolean | undefined;
   set 'active'(v: boolean);
   get 'hot'(): boolean | undefined;
   set 'hot'(v: boolean);
   /** Set one scalar parameter by name. */
   setParam(name: string, v: unknown): boolean;
   /** Resolve after the next retained solve and painted frame. */
   whenSettled(): Promise<void>;
   /** Read the last scalar parameter value accepted by this element. */
   getParam(name: string): unknown;
   /** Replace a root or nested list at its runtime path. */
   setList(name: string, path: string, v: unknown): boolean;
   /** Read the last root or nested list accepted at its runtime path. */
   getList(name: string, path: string): unknown;
}

/** Canonical full scene keys for authored `#id` nodes. */
export declare const SlabEGroupElementKeys: {
   readonly "panes": "EGroup@0/stack@0/#panes";
   readonly "kids": "EGroup@0/stack@0/#panes/#kids";
   readonly "chrome": "EGroup@0/stack@0/#chrome";
   readonly "strip": "EGroup@0/stack@0/#chrome/#strip";
   readonly "tabs": "EGroup@0/stack@0/#chrome/#strip/#tabs";
   readonly "crumb": "EGroup@0/stack@0/#chrome/#crumb";
   readonly "ed": "EGroup@0/stack@0/#chrome/#ed";
   readonly "content": "EGroup@0/stack@0/#chrome/#ed/#content";
   readonly "zone": "EGroup@0/stack@0/#chrome/#ed/#zone";
};
export type SlabEGroupElementSceneKey = (typeof SlabEGroupElementKeys)[keyof typeof SlabEGroupElementKeys];

/** Template-relative scene keys per `each` list; join with `itemKey`. */
export declare const SlabEGroupElementItemKeys: {
   readonly "kids": {
      readonly each: "EGroup@0/stack@0/#panes/#kids";
      readonly item: {
         readonly "panes": "stack@0/#panes";
         readonly "kids": "stack@0/#panes/#kids";
         readonly "chrome": "stack@0/#chrome";
         readonly "strip": "stack@0/#chrome/#strip";
         readonly "tabs": "stack@0/#chrome/#strip/#tabs";
         readonly "crumb": "stack@0/#chrome/#crumb";
         readonly "ed": "stack@0/#chrome/#ed";
         readonly "content": "stack@0/#chrome/#ed/#content";
         readonly "zone": "stack@0/#chrome/#ed/#zone";
      };
   };
   readonly "kids_2": {
      readonly each: "stack@0/#panes/#kids";
      readonly item: {
      };
   };
   readonly "tabs": {
      readonly each: "stack@0/#chrome/#strip/#tabs";
      readonly item: {
         readonly "body": "col@0/stack@0/#body";
         readonly "indl": "col@0/stack@0/#indl";
         readonly "indr": "col@0/stack@0/#indr";
      };
   };
   readonly "tabs_2": {
      readonly each: "EGroup@0/stack@0/#chrome/#strip/#tabs";
      readonly item: {
         readonly "body": "col@0/stack@0/#body";
         readonly "indl": "col@0/stack@0/#indl";
         readonly "indr": "col@0/stack@0/#indr";
      };
   };
};

export declare class SlabEGroupElement extends HTMLElement {
   /** Expose scene geometry on globalThis.__slabDebug for tests. */
   static debug: boolean;
   /** Current compiler-declared theme; empty means authored values. */
   get theme(): string;
   set theme(v: string);
   setTheme(name: string): boolean;
   getTheme(): string;
   /** Read one resolved token for the active theme. */
   getToken(path: string): string | number | undefined;
   /** Move focus to a keyed node; an empty key clears focus. */
   setFocus(key: string, visible?: boolean): boolean;
   /** Clear kernel focus and its visible focus ring. */
   clearFocus(): boolean;
   /** Reveal, materialize, and focus one virtual-list item. */
   focusItem(each: string, index: number): boolean;
   /** Explain the most recent failed focus request. */
   focusNote(): string;
   /** Return the focused scene key, or null when focus is clear. */
   focusedKey(): string | null;
   /** Report whether the focused node is an editable field. */
   inEditField(): boolean;
   /** Most recently painted frame, including complete diagnostics. */
   readonly lastFrame: SlabFrame | null;
   /** Cumulative per-instance diagnostics since the document mounted. */
   readonly diagnostics: readonly FrameDiagnostic[];
   addEventListener(type: 'slab-diagnostics', listener: (event: CustomEvent<SlabDiagnosticsDetail>) => void, options?: boolean | AddEventListenerOptions): void;
   /** Replace a keyed field buffer and reset its edit history. */
   setFieldText(key: string, text: string): boolean;
   /** Read a keyed field's committed text. */
   fieldText(key: string): string | undefined;
   /** Set a keyed scroll offset on axis 0 (main) or 1 (cross). */
   setScroll(key: string, axis: number, off: number): boolean;
   /** Read a keyed scroll offset on axis 0 (main) or 1 (cross). */
   getScroll(key: string, axis: number): number;
   /** Register or replace a named runtime image. */
   imgRegister(name: string, width: number, height: number, format: number, bytes: Uint8Array): number;
   /** Unregister a named runtime image. */
   imgUnregister(name: string): boolean;
   /** Read runtime or embedded image metadata by unified index. */
   imgInfo(image: number): readonly [width: number, height: number, format: number, generation: number] | null;
   /** Read runtime or embedded image bytes by unified index. */
   imgBytes(image: number): Uint8Array;
   /** Scroll ancestors minimally to reveal a keyed node. */
   reveal(key: string, margin: number): boolean;
   /** Reveal one virtual-list item using the requested alignment. */
   revealItem(each: string, index: number, align: number): boolean;
   /** Read a virtual list's materialized half-open item window. */
   eachWindow(each: string): readonly [start: number, end: number];
   /** Set the extent overlay controlled by a keyed divider. */
   setDivider(key: string, extent: number): boolean;
   /** Read a keyed divider's extent overlay. */
   getDivider(key: string): number;
   /** Set one retained split-pane size. */
   setSplit(paneKey: string, size: number): boolean;
   /** Read one retained split-pane size. */
   getSplit(paneKey: string): number;
   /** Set one host app state (selected, disabled, custom idents) on a keyed node. */
   setNodeState(key: string, name: string, on: boolean): boolean;
   /** Return the current retained scene, stable until the next solve. */
   sceneSnapshot(): readonly SceneNode[];
   get 'leaf'(): boolean | undefined;
   set 'leaf'(v: boolean);
   get 'horizontal'(): boolean | undefined;
   set 'horizontal'(v: boolean);
   get 'show_mdb'(): boolean | undefined;
   set 'show_mdb'(v: boolean);
   get 'show_store'(): boolean | undefined;
   set 'show_store'(v: boolean);
   get 'tabs'(): TabsItem[];
   set 'tabs'(v: TabsItem[]);
   get 'children'(): ChildrenItem[];
   set 'children'(v: ChildrenItem[]);
   /** Set one scalar parameter by name. */
   setParam(name: string, v: unknown): boolean;
   /** Resolve after the next retained solve and painted frame. */
   whenSettled(): Promise<void>;
   /** Read the last scalar parameter value accepted by this element. */
   getParam(name: string): unknown;
   /** Replace a root or nested list at its runtime path. */
   setList(name: string, path: string, v: unknown): boolean;
   /** Read the last root or nested list accepted at its runtime path. */
   getList(name: string, path: string): unknown;
}

/** Signal CustomEvent names → detail types. */
export declare const signals: {
   readonly 'tree_pick': SignalDetail;
   readonly 'sash_sidebar': TextSignalDetail;
   readonly 'split_resize': TextSignalDetail;
   readonly 'strip_new': SignalDetail;
   readonly 'strip_drop': SignalDetail;
   readonly 'tab_press': SignalDetail;
   readonly 'tab_dbl': SignalDetail;
   readonly 'tab_drag': SignalDetail;
   readonly 'tab_drop': SignalDetail;
   readonly 'tab_up': SignalDetail;
   readonly 'tab_move': SignalDetail;
   readonly 'tab_end': SignalDetail;
   readonly 'tab_close': SignalDetail;
   readonly 'editor_drop': SignalDetail;
   readonly 'find_change': TextSignalDetail;
   readonly 'sash_panel': TextSignalDetail;
   readonly 'panel_pick': SignalDetail;
   readonly 'filter_change': TextSignalDetail;
   readonly 'sash_center': TextSignalDetail;
   readonly 'chat_change': TextSignalDetail;
};
export type SignalName = keyof typeof signals;

declare global {
   interface HTMLElementTagNameMap {
      'slab-vscode': SlabVscodeElement;
      'slab-editor-tab': SlabEditorTabElement;
      'slab-e-group': SlabEGroupElement;
   }
}
