//! `cargo run -p xtask -- <cmd>` — repo tooling.
//!
//! `support-md` / `gen-caps` (src/support.rs) render spec/support.toml into
//! the SPEC.md platform-support chart and the generated caps tables.
//!
//! `gen-proto` emits the Rust protobuf bindings used by `slab-slir`.
//!
//! `abi-wasm` (`src/abi_wasm.rs`) builds the C-ABI WASM module the Go and
//! Python clients embed.

use std::path::PathBuf;
mod abi_wasm;
mod kernel_wasm;
mod support;

fn main() -> std::process::ExitCode {
	let args: Vec<String> = std::env::args().skip(1).collect();
	match args.first().map(String::as_str) {
		Some("gen-proto") => gen_proto(),
		Some("support-md") => support::cmd_support_md(),
		Some("gen-caps") => support::cmd_gen_caps(),
		Some("kernel-wasm") => command(|| kernel_wasm::run(&repo_root())),
		Some("abi-wasm") => command(|| abi_wasm::run(&repo_root())),
		_ => {
			eprintln!("usage: xtask gen-proto | support-md | gen-caps | kernel-wasm | abi-wasm");
			std::process::ExitCode::from(2)
		},
	}
}

fn command(run: impl FnOnce() -> Result<(), Box<dyn std::error::Error>>) -> std::process::ExitCode {
	match run() {
		Ok(()) => std::process::ExitCode::SUCCESS,
		Err(error) => {
			eprintln!("error: {error}");
			std::process::ExitCode::FAILURE
		},
	}
}

fn repo_root() -> PathBuf {
	// crates/xtask -> repo root
	PathBuf::from(env!("CARGO_MANIFEST_DIR"))
		.parent()
		.and_then(|p| p.parent())
		.expect("xtask lives two levels below the repo root")
		.to_path_buf()
}

fn gen_proto() -> std::process::ExitCode {
	match gen_proto_inner() {
		Ok(()) => std::process::ExitCode::SUCCESS,
		Err(error) => {
			eprintln!("error: {error}");
			std::process::ExitCode::FAILURE
		},
	}
}

fn gen_proto_inner() -> Result<(), Box<dyn std::error::Error>> {
	let root = repo_root();
	let out_dir = root.join("crates/slab-slir/src");
	let generated = out_dir.join("slir.rs");
	let descriptors = protox::compile([root.join("spec/slir.proto")], [root.join("spec")])?;
	let mut config = prost_build::Config::new();
	config.out_dir(&out_dir);
	config.compile_fds(descriptors)?;

	let generated_code = std::fs::read_to_string(&generated)?;
	let generated_code = generated_code
		.strip_prefix("// This file is @generated by prost-build.\n")
		.unwrap_or(&generated_code);
	std::fs::write(
		out_dir.join("pb.rs"),
		format!("// GENERATED by xtask gen-proto — do not edit.\n{generated_code}"),
	)?;
	std::fs::remove_file(generated)?;
	Ok(())
}
