// GENERATED by xtask gen-proto — do not edit.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Doc {
	#[prost(bool, tag = "1")]
	pub ok: bool,
	#[prost(string, repeated, tag = "2")]
	pub errs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
	#[prost(string, repeated, tag = "3")]
	pub strs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
	#[prost(uint32, repeated, tag = "4")]
	pub node_kind: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "5")]
	pub node_flags: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "6")]
	pub node_parent: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "7")]
	pub node_first: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "8")]
	pub node_next: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "9")]
	pub node_key: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "10")]
	pub node_id: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "11")]
	pub node_line: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "12")]
	pub aval_tag: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "13")]
	pub aval_lo: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "14")]
	pub aval_hi: ::prost::alloc::vec::Vec<u32>,
	#[prost(double, repeated, tag = "15")]
	pub aval_num: ::prost::alloc::vec::Vec<f64>,
	#[prost(double, repeated, tag = "16")]
	pub f64s: ::prost::alloc::vec::Vec<f64>,
	#[prost(uint32, repeated, tag = "17")]
	pub grad_kind: ::prost::alloc::vec::Vec<u32>,
	#[prost(double, repeated, tag = "18")]
	pub grad_angle: ::prost::alloc::vec::Vec<f64>,
	#[prost(int32, repeated, tag = "19")]
	pub grad_stop_off: ::prost::alloc::vec::Vec<i32>,
	#[prost(int32, repeated, tag = "20")]
	pub grad_stop_len: ::prost::alloc::vec::Vec<i32>,
	#[prost(double, repeated, tag = "21")]
	pub grad_stop_pos: ::prost::alloc::vec::Vec<f64>,
	#[prost(uint32, repeated, tag = "22")]
	pub grad_stop_rgba: ::prost::alloc::vec::Vec<u32>,
	#[prost(double, repeated, tag = "23")]
	pub shdw_x: ::prost::alloc::vec::Vec<f64>,
	#[prost(double, repeated, tag = "24")]
	pub shdw_y: ::prost::alloc::vec::Vec<f64>,
	#[prost(double, repeated, tag = "25")]
	pub shdw_blur: ::prost::alloc::vec::Vec<f64>,
	#[prost(double, repeated, tag = "26")]
	pub shdw_spread: ::prost::alloc::vec::Vec<f64>,
	#[prost(uint32, repeated, tag = "27")]
	pub shdw_rgba: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "28")]
	pub shdw_inset: ::prost::alloc::vec::Vec<u32>,
	#[prost(int32, repeated, tag = "29")]
	pub attr_index: ::prost::alloc::vec::Vec<i32>,
	#[prost(uint32, repeated, tag = "30")]
	pub attr_id: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "31")]
	pub attr_val: ::prost::alloc::vec::Vec<u32>,
	#[prost(int32, repeated, tag = "32")]
	pub path_verb_off: ::prost::alloc::vec::Vec<i32>,
	#[prost(int32, repeated, tag = "33")]
	pub path_verb_len: ::prost::alloc::vec::Vec<i32>,
	#[prost(int32, repeated, tag = "34")]
	pub path_coord_off: ::prost::alloc::vec::Vec<i32>,
	#[prost(int32, repeated, tag = "35")]
	pub path_coord_len: ::prost::alloc::vec::Vec<i32>,
	#[prost(uint32, repeated, tag = "36")]
	pub path_verbs: ::prost::alloc::vec::Vec<u32>,
	#[prost(double, repeated, tag = "37")]
	pub path_coords: ::prost::alloc::vec::Vec<f64>,
	#[prost(uint32, repeated, tag = "38")]
	pub font_family: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "39")]
	pub font_class: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "40")]
	pub font_weight: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "41")]
	pub font_upem: ::prost::alloc::vec::Vec<u32>,
	#[prost(int32, repeated, tag = "42")]
	pub font_ascent: ::prost::alloc::vec::Vec<i32>,
	#[prost(int32, repeated, tag = "43")]
	pub font_descent: ::prost::alloc::vec::Vec<i32>,
	#[prost(int32, repeated, tag = "44")]
	pub font_line_gap: ::prost::alloc::vec::Vec<i32>,
	#[prost(uint32, repeated, tag = "45")]
	pub font_default_adv: ::prost::alloc::vec::Vec<u32>,
	#[prost(int32, repeated, tag = "46")]
	pub font_cmap_off: ::prost::alloc::vec::Vec<i32>,
	#[prost(int32, repeated, tag = "47")]
	pub font_cmap_len: ::prost::alloc::vec::Vec<i32>,
	#[prost(uint32, repeated, tag = "48")]
	pub font_cmap_cp: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "49")]
	pub font_cmap_gid: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "50")]
	pub font_adv: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "51")]
	pub cond_kind: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "52")]
	pub cond_neg: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "53")]
	pub cond_op: ::prost::alloc::vec::Vec<u32>,
	#[prost(double, repeated, tag = "54")]
	pub cond_num: ::prost::alloc::vec::Vec<f64>,
	#[prost(uint32, repeated, tag = "55")]
	pub cond_sym: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "56")]
	pub patch_node: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "57")]
	pub patch_cond: ::prost::alloc::vec::Vec<u32>,
	#[prost(int32, repeated, tag = "58")]
	pub patch_attr_off: ::prost::alloc::vec::Vec<i32>,
	#[prost(int32, repeated, tag = "59")]
	pub patch_attr_len: ::prost::alloc::vec::Vec<i32>,
	#[prost(int32, repeated, tag = "60")]
	pub patch_child_off: ::prost::alloc::vec::Vec<i32>,
	#[prost(int32, repeated, tag = "61")]
	pub patch_child_len: ::prost::alloc::vec::Vec<i32>,
	#[prost(uint32, repeated, tag = "62")]
	pub wattr_id: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "63")]
	pub wattr_val: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "64")]
	pub patch_children: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "65")]
	pub anim_name: ::prost::alloc::vec::Vec<u32>,
	#[prost(int32, repeated, tag = "66")]
	pub anim_stop_off: ::prost::alloc::vec::Vec<i32>,
	#[prost(int32, repeated, tag = "67")]
	pub anim_stop_len: ::prost::alloc::vec::Vec<i32>,
	#[prost(double, repeated, tag = "68")]
	pub anim_stop_pos: ::prost::alloc::vec::Vec<f64>,
	#[prost(int32, repeated, tag = "69")]
	pub anim_stop_attr_off: ::prost::alloc::vec::Vec<i32>,
	#[prost(int32, repeated, tag = "70")]
	pub anim_stop_attr_len: ::prost::alloc::vec::Vec<i32>,
	#[prost(uint32, repeated, tag = "71")]
	pub aattr_id: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "72")]
	pub aattr_val: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "73")]
	pub bind_node: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "74")]
	pub bind_anim: ::prost::alloc::vec::Vec<u32>,
	#[prost(double, repeated, tag = "75")]
	pub bind_dur: ::prost::alloc::vec::Vec<f64>,
	#[prost(uint32, repeated, tag = "76")]
	pub bind_mode: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "77")]
	pub bind_easing: ::prost::alloc::vec::Vec<u32>,
	#[prost(double, repeated, tag = "78")]
	pub bind_delay: ::prost::alloc::vec::Vec<f64>,
	#[prost(uint32, repeated, tag = "79")]
	pub trans_node: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "80")]
	pub trans_easing: ::prost::alloc::vec::Vec<u32>,
	#[prost(double, repeated, tag = "81")]
	pub trans_dur: ::prost::alloc::vec::Vec<f64>,
	#[prost(double, repeated, tag = "82")]
	pub trans_delay: ::prost::alloc::vec::Vec<f64>,
	#[prost(uint32, repeated, tag = "83")]
	pub parm_name: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "84")]
	pub parm_type: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "85")]
	pub parm_default: ::prost::alloc::vec::Vec<u32>,
	#[prost(int32, repeated, tag = "86")]
	pub parm_enum_off: ::prost::alloc::vec::Vec<i32>,
	#[prost(int32, repeated, tag = "87")]
	pub parm_enum_len: ::prost::alloc::vec::Vec<i32>,
	#[prost(int32, repeated, tag = "88")]
	pub parm_site_off: ::prost::alloc::vec::Vec<i32>,
	#[prost(int32, repeated, tag = "89")]
	pub parm_site_len: ::prost::alloc::vec::Vec<i32>,
	#[prost(uint32, repeated, tag = "90")]
	pub parm_enum_syms: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "91")]
	pub parm_site_node: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "92")]
	pub parm_site_attr: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "93")]
	pub list_param: ::prost::alloc::vec::Vec<u32>,
	#[prost(int32, repeated, tag = "94")]
	pub list_field_off: ::prost::alloc::vec::Vec<i32>,
	#[prost(int32, repeated, tag = "95")]
	pub list_field_len: ::prost::alloc::vec::Vec<i32>,
	#[prost(uint32, repeated, tag = "96")]
	pub list_field_name: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "97")]
	pub list_field_type: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "98")]
	pub list_field_default: ::prost::alloc::vec::Vec<u32>,
	#[prost(int32, repeated, tag = "99")]
	pub list_field_enum_off: ::prost::alloc::vec::Vec<i32>,
	#[prost(int32, repeated, tag = "100")]
	pub list_field_enum_len: ::prost::alloc::vec::Vec<i32>,
	#[prost(uint32, repeated, tag = "101")]
	pub list_enum_syms: ::prost::alloc::vec::Vec<u32>,
	#[prost(int32, repeated, tag = "102")]
	pub list_item_field_off: ::prost::alloc::vec::Vec<i32>,
	#[prost(int32, repeated, tag = "103")]
	pub list_item_field_len: ::prost::alloc::vec::Vec<i32>,
	#[prost(uint32, repeated, tag = "104")]
	pub list_item_value_field: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "105")]
	pub list_item_value_val: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "106")]
	pub theme_name: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "107")]
	pub hole_name: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "108")]
	pub hole_node: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "109")]
	pub sign_name: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "110")]
	pub sign_node: ::prost::alloc::vec::Vec<u32>,
	/// Binder kind per signal: 0 activate, 1 change, 2 submit, 3 press,
	/// 4 context, 5 dblclick, 6 drag-start, 7 drop, 8 resize, 9 pointer-move,
	/// 10 pointer-up, 11 drag-update, 12 drag-end, 13 typed-keys activate,
	/// 14 cancel (escape-blur discard; carries the retained buffer text).
	#[prost(uint32, repeated, tag = "111")]
	pub sign_trigger: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "112")]
	pub img_src: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "113")]
	pub img_w: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "114")]
	pub img_h: ::prost::alloc::vec::Vec<u32>,
	#[prost(uint32, repeated, tag = "115")]
	pub img_format: ::prost::alloc::vec::Vec<u32>,
	#[prost(bytes = "vec", repeated, tag = "116")]
	pub img_data: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
	#[prost(uint32, repeated, tag = "117")]
	pub tup_dyn_tag: ::prost::alloc::vec::Vec<u32>,
	#[prost(double, repeated, tag = "118")]
	pub tup_dyn_num: ::prost::alloc::vec::Vec<f64>,
	#[prost(uint32, repeated, tag = "119")]
	pub tup_dyn_param: ::prost::alloc::vec::Vec<u32>,
	/// 0 scalar, n+1 nested list-schema row
	#[prost(uint32, repeated, tag = "120")]
	pub list_field_sub: ::prost::alloc::vec::Vec<u32>,
	/// STRS ref
	#[prost(uint32, repeated, tag = "121")]
	pub icon_name: ::prost::alloc::vec::Vec<u32>,
	/// detached subtree root
	#[prost(uint32, repeated, tag = "122")]
	pub icon_node: ::prost::alloc::vec::Vec<u32>,
	/// square design-box size, default 24
	#[prost(double, repeated, tag = "123")]
	pub icon_viewbox: ::prost::alloc::vec::Vec<f64>,
	/// STRS ref, dotted path
	#[prost(uint32, repeated, tag = "130")]
	pub token_name: ::prost::alloc::vec::Vec<u32>,
	/// AVAL ref
	#[prost(uint32, repeated, tag = "131")]
	pub token_base: ::prost::alloc::vec::Vec<u32>,
	/// slice into `token_theme_name/val`
	#[prost(int32, repeated, tag = "132")]
	pub token_theme_off: ::prost::alloc::vec::Vec<i32>,
	#[prost(int32, repeated, tag = "133")]
	pub token_theme_len: ::prost::alloc::vec::Vec<i32>,
	/// STRS ref
	#[prost(uint32, repeated, tag = "134")]
	pub token_theme_name: ::prost::alloc::vec::Vec<u32>,
	/// AVAL ref
	#[prost(uint32, repeated, tag = "135")]
	pub token_theme_val: ::prost::alloc::vec::Vec<u32>,
	/// STRS ref, canonical host text
	#[prost(uint32, repeated, tag = "136")]
	pub token_base_repr: ::prost::alloc::vec::Vec<u32>,
	/// STRS ref parallel to `token_theme_val`
	#[prost(uint32, repeated, tag = "137")]
	pub token_theme_repr: ::prost::alloc::vec::Vec<u32>,
	#[prost(int32, repeated, tag = "138")]
	pub font_underline_position: ::prost::alloc::vec::Vec<i32>,
	#[prost(int32, repeated, tag = "139")]
	pub font_underline_thickness: ::prost::alloc::vec::Vec<i32>,
}
