[package]
name = "slab-native"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "slab_native"
path = "src/lib.rs"

[[bin]]
name = "slab-native"
path = "src/main.rs"

[dependencies]
slab-kernel = { path = "../slab-kernel" }
slab-compile = { path = "../slab-compile" }
slab-slir = { path = "../slab-slir" }
slab-drive = { path = "../slab-drive" }
slab-fonts = { path = "../slab-fonts" }
winit = { workspace = true }
wgpu = { workspace = true }
accesskit = { workspace = true }
accesskit_winit = { workspace = true }
ab_glyph = { workspace = true }
lyon = { workspace = true }
png = { workspace = true }
bytemuck = { workspace = true }
pollster = { workspace = true }

arboard = { version = "3.6.1", default-features = false }

[target.'cfg(unix)'.dependencies]
signal-hook = "0.3"