[package]
name = "slab-native"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "slab_native"
path = "src/lib.rs"

[[bin]]
name = "slab-native"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
ab_glyph.workspace = true
accesskit.workspace = true
accesskit_winit.workspace = true
arboard.workspace = true
bytemuck.workspace = true
lyon.workspace = true
png.workspace = true
pollster.workspace = true
slab-compile.workspace = true
slab-drive.workspace = true
slab-fonts.workspace = true
slab-kernel.workspace = true
slab-slir.workspace = true
wgpu.workspace = true
winit.workspace = true

[target.'cfg(unix)'.dependencies]
signal-hook.workspace = true
