use slab_compile::{
    Options,
    export::{ExportProp, compile_export},
};
use slab_slir::{Aval, Slir, aval};
use slab_syntax::ast::ParamType;

fn compile_export_ok(source: &str, name: &str) -> (Slir, Vec<ExportProp>) {
    let (slir, diagnostics, props) = compile_export(
        source,
        name,
        &Options {
            embed_assets: false,
            ..Options::default()
        },
    );
    assert!(!diagnostics.has_errors(), "{:#?}", diagnostics.0);
    (slir.expect("valid exported def"), props)
}

fn prop_type<'a>(props: &'a [ExportProp], name: &str) -> &'a ParamType {
    &props
        .iter()
        .find(|prop| prop.name == name)
        .unwrap_or_else(|| panic!("missing exported prop {name}"))
        .ty
}

fn param_default(slir: &Slir, name: &str) -> Aval {
    let param = slir
        .params
        .iter()
        .find(|param| slir.str_at(param.name) == name)
        .unwrap_or_else(|| panic!("missing exported param {name}"));
    slir.avals[param.default as usize]
}

#[test]
fn checked_uses_boolean_inference_from_default_and_when_vote() {
    let source = r#"
def Toggle(on=false) export {
  col checked=on {
    when on { bg=#ffffff }
  }
}
"#;
    let (slir, props) = compile_export_ok(source, "Toggle");

    assert!(matches!(prop_type(&props, "on"), ParamType::Bool));
    let param = slir
        .params
        .iter()
        .find(|param| slir.str_at(param.name) == "on")
        .expect("exported on param");
    assert_eq!(param.ty, 4);
    let default = param_default(&slir, "on");
    assert_eq!(default.tag, aval::NUM);
    assert_eq!(default.as_f64(), 0.0);
}

#[test]
fn named_checked_and_live_defaults_remain_text() {
    let source = r#"
def Status(checked=mixed, live=polite) export {
  col checked=checked live=live
}
"#;
    let (slir, props) = compile_export_ok(source, "Status");

    assert!(matches!(prop_type(&props, "checked"), ParamType::Text));
    assert!(matches!(prop_type(&props, "live"), ParamType::Text));
    for (name, expected) in [("checked", "mixed"), ("live", "polite")] {
        let default = param_default(&slir, name);
        assert_eq!(default.tag, aval::STR);
        assert_eq!(slir.str_at(default.lo()), expected);
    }
}

#[test]
fn rust_generator_keeps_source_name_in_header() {
    let source = "col { text \"ok\" }\n";
    let (module, diagnostics) =
        slab_compile::rustgen::generate(source, &Options::default(), "todo.slab");
    assert!(!diagnostics.has_errors(), "{:?}", diagnostics.0);
    let module = module.expect("generated module");
    assert!(
        module.starts_with("// GENERATED by `slab gen rust todo.slab`"),
        "{}",
        module.lines().next().unwrap_or_default()
    );
}
