[package]
name = "slab-lsp"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
slab-syntax = { path = "../slab-syntax" }
slab-slir = { path = "../slab-slir" }
slab-compile = { path = "../slab-compile" }
slab-kernel = { path = "../slab-kernel" }
serde_json.workspace = true
