import { afterEach, describe, expect, test } from 'bun:test';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
   compileSlab,
   declarationPath,
   hmrFooter,
   SlabCompileError,
   toDeclaration,
   writeDeclaration,
} from '../src/core.ts';

const FIXTURE = fileURLToPath(new URL('./fixtures/hello.slab', import.meta.url));
const SOURCE = readFileSync(FIXTURE, 'utf8');

// 1x1 black PNG.
const DOT_PNG = Buffer.from(
   'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==',
   'base64',
);

const roots: string[] = [];
afterEach(() => {
   for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true });
});

function tempDir(): string {
   const root = mkdtempSync(join(tmpdir(), 'slab-plugin-test-'));
   roots.push(root);
   return root;
}

describe('compileSlab', () => {
   test('emits the module with the runtime import rewritten to @stencil-hq/wslab', () => {
      const mod = compileSlab(FIXTURE, SOURCE);
      expect(mod.code).toContain("import { SlabElement } from '@stencil-hq/wslab';");
      expect(mod.code).not.toContain('./slab-runtime.js');
      expect(mod.code).toContain('export class SlabHelloElement extends SlabElement');
      expect(mod.code).toContain(
         "if (!customElements.get('slab-hello')) customElements.define('slab-hello', SlabHelloElement);",
      );
      expect(mod.code).toContain('export const signals');
      expect(mod.tags).toEqual([{ tag: 'slab-hello', className: 'SlabHelloElement' }]);
      expect(mod.warnings).toEqual([]);
      expect(mod.assets).toEqual([]);
   });

   test('collects referenced image assets and reports their paths', () => {
      const root = tempDir();
      writeFileSync(join(root, 'dot.png'), DOT_PNG);
      const file = join(root, 'card.slab');
      const source = 'col w=fill pad=8 {\n  img src="dot.png" w=8 h=8\n}\n';
      writeFileSync(file, source);
      const mod = compileSlab(file, source);
      expect(mod.assets).toEqual([join(root, 'dot.png')]);
   });

   test('leaves missing assets to the compiler warning path', () => {
      const root = tempDir();
      const file = join(root, 'card.slab');
      const source = 'col w=fill pad=8 {\n  img src="gone.png" w=8 h=8\n}\n';
      writeFileSync(file, source);
      const mod = compileSlab(file, source);
      expect(mod.assets).toEqual([]);
      expect(mod.warnings.some((d) => d.level !== 'error')).toBe(true);
   });

   test('throws SlabCompileError carrying formatted diagnostics on compile failure', () => {
      const broken = 'col w=fill {\n  glyph "nope"\n}\n';
      let thrown: unknown;
      try {
         compileSlab('/tmp/bad.slab', broken);
      } catch (error) {
         thrown = error;
      }
      expect(thrown).toBeInstanceOf(SlabCompileError);
      const error = thrown as SlabCompileError;
      expect(error.message).toContain("unknown node 'glyph'");
      expect(error.diagnostics.length).toBeGreaterThan(0);
      expect(error.diagnostics[0]?.level).toBe('error');
   });
});

describe('declarations', () => {
   test('declarationPath maps app.slab to app.d.slab.ts', () => {
      expect(declarationPath('/x/app.slab')).toBe('/x/app.d.slab.ts');
   });

   test('toDeclaration keeps class and signals exports, free of relative modules', () => {
      const mod = compileSlab(FIXTURE, SOURCE);
      const decl = toDeclaration(mod.dts);
      expect(decl.startsWith('// GENERATED by @stencil-hq/slab-plugin — do not edit.\n')).toBe(
         true,
      );
      expect(decl).toContain('export declare class SlabHelloElement extends HTMLElement');
      expect(decl).toContain('export declare const signals');
      expect(decl).toContain("'slab-hello': SlabHelloElement;");
      expect(decl).not.toContain("from '.");
      expect(decl).not.toContain('import ');
   });

   test('writeDeclaration writes once and skips byte-identical content', () => {
      const root = tempDir();
      const file = join(root, 'app.slab');
      expect(writeDeclaration(file, 'content-a')).toBe(true);
      expect(readFileSync(join(root, 'app.d.slab.ts'), 'utf8')).toBe('content-a');
      expect(writeDeclaration(file, 'content-a')).toBe(false);
      expect(writeDeclaration(file, 'content-b')).toBe(true);
      expect(readFileSync(join(root, 'app.d.slab.ts'), 'utf8')).toBe('content-b');
   });
});

describe('hmrFooter', () => {
   test('self-accepts and swaps bytes through the registered class', () => {
      const footer = hmrFooter([{ tag: 'slab-hello', className: 'SlabHelloElement' }]);
      expect(footer).toContain('import.meta.hot.accept();');
      expect(footer).toContain("['slab-hello', SlabHelloElement]");
      expect(footer).toContain('current.hotReplaceSlir(bytes);');
      expect(footer).toContain('el.loadSlir(bytes)');
   });
});
