[package]
name = "slab-kernel-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
slab-kernel.workspace = true
slab-slir.workspace = true
wasm-bindgen.workspace = true
