#!/usr/bin/env bun
// Emits crates/slab-native/src/vscode_fs.rs from web/fsmodel.js so the native
// host shares the web demo's file tree and file contents verbatim.
// Run: bun demos/vscode/gen_fs.ts
import { resolve } from 'node:path';

import { writeGenerated } from '../../scripts/generation.ts';
import { CONTENTS, DEFAULT_OPEN, FILES } from './web/fsmodel.js';

const ROOT = resolve(import.meta.dirname, '../..');

interface FsNode {
   name: string;
   path: string;
   dir: boolean;
   letter: string;
   icon: string;
   tint: string;
   badge: string;
   children?: FsNode[];
}

const flat: Array<FsNode & { depth: number }> = [];
const visit = (nodes: FsNode[], depth: number) => {
   for (const node of nodes) {
      flat.push({ ...node, depth });
      if (node.dir && node.children) visit(node.children, depth + 1);
   }
};
visit(FILES as FsNode[], 0);

function rawString(text: string): string {
	let hashes = 0;
	if (text.includes('"')) {
		hashes = 1;
		while (text.includes(`"${'#'.repeat(hashes)}`)) hashes += 1;
	}
	const h = '#'.repeat(hashes);
	return `r${h}"${text}"${h}`;
}

const lines: string[] = [];
lines.push('// GENERATED by `bun demos/vscode/gen_fs.ts` from demos/vscode/web/fsmodel.js — do not edit.');
lines.push('');
lines.push('//! Static file-system model for the native VS Code demo, shared verbatim');
lines.push('//! with the web host (`demos/vscode/web/fsmodel.js`).');
lines.push('');
lines.push('/// One explorer entry, depth-first with parents before children.');
lines.push('pub struct FsEntry {');
lines.push('\tpub path:   &\'static str,');
lines.push('\tpub name:   &\'static str,');
lines.push('\tpub letter: &\'static str,');
lines.push('\tpub icon:   &\'static str,');
lines.push('\tpub tint:   &\'static str,');
lines.push('\tpub badge:  &\'static str,');
lines.push('\tpub dir:    bool,');
lines.push('\tpub depth:  u32,');
lines.push('}');
lines.push('');
lines.push('/// The explorer tree, flattened depth-first.');
lines.push('pub static ENTRIES: &[FsEntry] = &[');
for (const node of flat) {
   lines.push(
      `\tFsEntry { path: ${JSON.stringify(node.path)}, name: ${JSON.stringify(node.name)}, ` +
         `letter: ${JSON.stringify(node.letter)}, icon: ${JSON.stringify(node.icon)}, ` +
         `tint: ${JSON.stringify(node.tint)}, badge: ${JSON.stringify(node.badge)}, ` +
         `dir: ${node.dir}, depth: ${node.depth} },`,
   );
}
lines.push('];');
lines.push('');
lines.push('/// Directories open at first launch.');
lines.push(`pub static DEFAULT_OPEN: &[&str] = &[${[...DEFAULT_OPEN].map((p: string) => JSON.stringify(p)).join(', ')}];`);
lines.push('');
lines.push('/// Initial file contents by path.');
lines.push('pub static CONTENTS: &[(&str, &str)] = &[');
const contents = CONTENTS as Record<string, string>;
for (const path in contents) {
	const content = contents[path];
	lines.push(`\t(${JSON.stringify(path)}, ${rawString(content)}),`);
}
lines.push('];');
lines.push('');

const source = new TextEncoder().encode(lines.join('\n'));
const formatted = Bun.spawnSync({
   cmd: ['rustfmt', '--edition', '2024', '--emit', 'stdout', '--config-path', ROOT],
   cwd: ROOT,
   stdin: source,
   stdout: 'pipe',
   stderr: 'inherit',
   maxBuffer: 1024 * 1024,
});
if (formatted.exitCode !== 0) {
   console.error(`gen_fs: rustfmt exited with ${formatted.exitCode}`);
   process.exit(1);
}
const destination = new URL('../../crates/slab-native/src/vscode_fs.rs', import.meta.url);
const changed = writeGenerated(destination, formatted.stdout);
console.log(
   `${changed ? 'wrote' : 'unchanged'} vscode_fs.rs: ${flat.length} entries, ${Object.keys(CONTENTS).length} files`,
);
