[package]
name = "slab-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "slab-tui"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
crossterm.workspace = true
slab-compile.workspace = true
slab-kernel.workspace = true
slab-slir.workspace = true
