// GENERATED by `slab gen rust examples/00-player.slab` — do not edit.
// Regenerate: cargo run -q -p slab-cli -- gen rust examples/00-player.slab -o
// <this file> && cargo fmt
#![allow(
	clippy::derive_partial_eq_without_eq,
	clippy::use_self,
	clippy::doc_markdown,
	reason = "generated module favors uniform emission over per-document lint shape"
)]

use slab_kernel::{
	dispatch::{Effects, Event},
	flatten::Frame,
	frame::{self as kframe, HoleRect, Instance, ParamValue},
};
use slab_slir;

/// The compiled SLIR document (25106 bytes).
pub static SLIR: &[u8] = include_bytes!("gen_player.slir");

/// Packed SLIR color word (red in the low byte, then green, blue, alpha).
pub type Rgba = u32;

/// Pack straight-alpha RGBA channels for generated color params and list
/// fields.
pub const fn rgba(red: u8, green: u8, blue: u8, alpha: u8) -> Rgba {
	u32::from_le_bytes([red, green, blue, alpha])
}

/// Canonical full scene keys for authored `#id` nodes.
pub mod keys {
	pub const PLAYER: &str = "#player";
	pub const SHUFFLE: &str = "#player/row@0/row@0/#shuffle";
	pub const PREV: &str = "#player/row@0/row@0/#prev";
	pub const PLAY: &str = "#player/row@0/row@0/#play";
	pub const NEXT: &str = "#player/row@0/row@0/#next";
	pub const LOOP: &str = "#player/row@0/row@0/#loop";

	/// Join one `each` item into a full canonical scene key.
	///
	/// `item_key(EACH, item, "")` addresses the item root; a non-empty
	/// `rel` appends a template-relative key. `item` is escaped per the
	/// canonical grammar (`%` → `%25`, `/` → `%2F`, `~` → `%7E`).
	pub fn item_key(each: &str, item: &str, rel: &str) -> String {
		let mut escaped = String::with_capacity(item.len());
		for ch in item.chars() {
			match ch {
				'%' => escaped.push_str("%25"),
				'/' => escaped.push_str("%2F"),
				'~' => escaped.push_str("%7E"),
				_ => escaped.push(ch),
			}
		}
		if rel.is_empty() {
			format!("{each}~{escaped}")
		} else {
			format!("{each}~{escaped}/{rel}")
		}
	}
}

pub const PARAM_TITLE: u32 = 0;
pub const PARAM_ARTIST: u32 = 1;
pub const PARAM_ELAPSED: u32 = 2;
pub const PARAM_REMAIN: u32 = 3;
pub const PARAM_PROGRESS: u32 = 4;
pub const PARAM_PLAYING: u32 = 5;
pub const HOLE_QUEUE: u32 = 0;
const SIG_SHUFFLE: u32 = 113;
const SIG_PREV: u32 = 121;
const SIG_TOGGLE: u32 = 127;
const SIG_NEXT: u32 = 135;
const SIG_LOOP: u32 = 140;

/// Metadata captured for every emitted signal.
#[derive(Debug, Clone, PartialEq)]
pub struct SignalMeta {
	/// Document-space pointer x, or `-1.0` for keyboard origin.
	pub x:           f64,
	/// Document-space pointer y, or `-1.0` for keyboard origin.
	pub y:           f64,
	/// Horizontal delta carried by the originating event.
	pub dx:          f64,
	/// Vertical delta carried by the originating event.
	pub dy:          f64,
	/// Horizontal drag displacement from the pointer-down origin.
	pub drag_dx:     f64,
	/// Vertical drag displacement from the pointer-down origin.
	pub drag_dy:     f64,
	/// Modifier bitset active at emission.
	pub mods:        u32,
	/// Pointer button code.
	pub button:      u32,
	/// Host-computed click count.
	pub clicks:      u32,
	/// Full key path of the signal-emitting node.
	pub key:         String,
	/// Full drag-source key for Drop, otherwise empty.
	pub src_key:     String,
	/// Innermost drag-source item key for `Drop`, otherwise empty.
	pub src_item:    String,
	/// Whether `DragEnd` represents abnormal termination.
	pub cancelled:   bool,
	/// Whether `DragEnd` delivered `Drop` to an eligible target.
	pub dropped:     bool,
	/// Deepest hit-target key on pointer-derived signals, otherwise empty.
	pub hit_key:     String,
	/// Pressed key name on keyboard-driven activation, otherwise empty.
	pub pressed_key: String,
}

impl From<&slab_kernel::dispatch::SigMeta> for SignalMeta {
	fn from(meta: &slab_kernel::dispatch::SigMeta) -> Self {
		Self {
			x:           meta.x,
			y:           meta.y,
			dx:          meta.dx,
			dy:          meta.dy,
			drag_dx:     meta.drag_dx,
			drag_dy:     meta.drag_dy,
			mods:        meta.mods,
			button:      meta.button,
			clicks:      meta.clicks,
			key:         meta.key.clone(),
			src_key:     meta.src_key.clone(),
			src_item:    meta.src_item.clone(),
			cancelled:   meta.cancelled,
			dropped:     meta.dropped,
			hit_key:     meta.hit_key.clone(),
			pressed_key: meta.pressed_key.clone(),
		}
	}
}

/// Signals declared in the document's SIGN table.
#[derive(Debug, Clone, PartialEq)]
pub enum Signal {
	/// A signal carrying list identity and input metadata.
	Shuffle {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	Prev {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	Toggle {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	Next {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	Loop {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
}

/// Names accepted by the document's signal surface.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub enum SignalName {
	Shuffle,
	Prev,
	Toggle,
	Next,
	Loop,
}

impl SignalName {
	/// Return the authored signal name.
	pub const fn as_str(self) -> &'static str {
		match self {
			Self::Shuffle => "shuffle",
			Self::Prev => "prev",
			Self::Toggle => "toggle",
			Self::Next => "next",
			Self::Loop => "loop",
		}
	}
}

/// The document instance, driven through `slab-kernel`.
pub struct Doc {
	/// Raw kernel instance for advanced integrations.
	pub inst: Instance,
	/// Image bytes carried by the compiled document.
	pub imgs: Vec<Vec<u8>>,
}

impl Default for Doc {
	fn default() -> Self {
		Self::new()
	}
}

impl Doc {
	/// Create an instance initialized from the included document.
	pub fn new() -> Self {
		let (doc, imgs) = slab_slir::decode_doc(SLIR).expect("included SLIR");
		let inst = kframe::inst_from_doc(doc);
		Self { inst, imgs }
	}

	/// Whether the included document decoded successfully.
	pub const fn ok(&self) -> bool {
		self.inst.ok
	}

	/// Env for the gpu client (client code 1); portrait derives from vw < vh.
	pub fn set_env(&mut self, vw: f64, vh: f64, dark: bool, coarse: bool) {
		kframe::inst_set_env(&mut self.inst, vw, vh, 1, dark, coarse);
	}

	/// Select a compiler-declared theme; an empty name restores authored values.
	pub fn set_theme(&mut self, name: &str) -> bool {
		kframe::inst_set_theme(&mut self.inst, name)
	}

	/// Drop generated list reconciliation snapshots after an external document
	/// reload. Call this when a host-mounted `RequestPump` reports `reloaded ==
	/// true`, before re-synchronizing typed list setters. Safe and idempotent.
	#[allow(
		clippy::missing_const_for_fn,
		reason = "documents without list params leave this body empty"
	)]
	pub fn invalidate_caches(&mut self) {}

	/// Read one token resolved through the active theme, with base fallback.
	pub fn get_token(&self, path: &str) -> Option<kframe::TokenValue<'_>> {
		kframe::inst_get_token(&self.inst, path)
	}

	/// Move focus to a keyed focusable node; an empty key clears focus.
	/// `visible` shows the keyboard-grade focus ring.
	pub fn set_focus(&mut self, key: &str, visible: bool) -> bool {
		kframe::inst_set_focus(&mut self.inst, key, visible)
	}

	/// Clear focus while retaining field edit buffers.
	pub fn clear_focus(&mut self) -> bool {
		kframe::inst_clear_focus(&mut self.inst)
	}

	/// Focus and reveal a concrete item in an `each` list.
	pub fn focus_item(&mut self, each_key: &str, index: i32) -> bool {
		kframe::inst_focus_item(&mut self.inst, each_key, index)
	}

	/// Explain the most recent failed focus operation.
	pub fn focus_note(&self) -> &str {
		kframe::inst_focus_note(&self.inst)
	}

	/// Replace a keyed field buffer, reset its edit history, and emit Change.
	pub fn set_field_text(&mut self, key: &str, text: &str) -> bool {
		kframe::inst_set_field_text(&mut self.inst, key, text)
	}

	/// Return a keyed field's committed text, or `None` for a non-field key.
	pub fn field_text(&self, key: &str) -> Option<String> {
		kframe::inst_field_text(&self.inst, key)
	}

	/// Current theme name; empty means the authored base.
	pub fn theme(&self) -> String {
		kframe::inst_theme(&self.inst)
	}

	/// Solve and flatten the document at `t_ms` milliseconds.
	pub fn frame(&mut self, t_ms: f64) -> Frame {
		kframe::inst_frame(&mut self.inst, t_ms)
	}

	/// Return the current host-content hole rectangles.
	pub fn holes(&mut self) -> Vec<HoleRect> {
		kframe::inst_holes(&mut self.inst)
	}

	/// Set a keyed scroll node's offset on axis 0 (main) or 1 (cross).
	pub fn set_scroll(&mut self, key: &str, axis: u32, off: f64) -> bool {
		kframe::inst_set_scroll(&mut self.inst, key, axis, off)
	}

	/// Read a keyed scroll node's offset on axis 0 (main) or 1 (cross).
	pub fn get_scroll(&self, key: &str, axis: u32) -> f64 {
		kframe::inst_get_scroll(&self.inst, key, axis)
	}

	/// Register or replace a named runtime image and return its unified image
	/// index.
	pub fn img_register(&mut self, name: &str, w: u32, h: u32, format: u32, data: &[u8]) -> i32 {
		kframe::inst_img_register(&mut self.inst, name, w, h, format, data)
	}

	/// Unregister a named runtime image while preserving its unified image
	/// index.
	pub fn img_unregister(&mut self, name: &str) -> bool {
		kframe::inst_img_unregister(&mut self.inst, name)
	}

	/// Scroll ancestors minimally to reveal a keyed node with the requested
	/// margin.
	pub fn reveal(&mut self, key: &str, margin: f64) -> bool {
		kframe::inst_reveal(&mut self.inst, key, margin)
	}

	/// Reveal an item in a virtual list using start, center, end, or nearest
	/// alignment.
	pub fn reveal_item(&mut self, each_key: &str, index: i32, align: u32) -> bool {
		kframe::inst_reveal_item(&mut self.inst, each_key, index, align)
	}

	/// Return a virtual list's materialized half-open item window.
	pub fn each_window(&self, each_key: &str) -> (i32, i32) {
		kframe::inst_each_window(&self.inst, each_key)
	}

	/// Enable retained per-item extents and update one virtual-list item.
	pub fn set_item_extent(&mut self, each_key: &str, index: i32, extent: f64) -> bool {
		kframe::inst_set_item_extent(&mut self.inst, each_key, index, extent)
	}

	/// Set the extent overlay controlled by a keyed divider.
	pub fn set_divider(&mut self, key: &str, extent: f64) -> bool {
		kframe::inst_set_divider(&mut self.inst, key, extent)
	}

	/// Read a keyed divider's extent overlay, or `-1.0` when unknown or unset.
	pub fn get_divider(&self, key: &str) -> f64 {
		kframe::inst_get_divider(&self.inst, key)
	}

	/// Set one retained split-pane size.
	pub fn set_split(&mut self, pane_key: &str, size: f64) -> bool {
		kframe::inst_set_split(&mut self.inst, pane_key, size)
	}

	/// Read one retained split-pane size, or `-1.0` when unknown.
	pub fn get_split(&self, pane_key: &str) -> f64 {
		kframe::inst_get_split(&self.inst, pane_key)
	}

	/// Dispatch an input event and return its raw and typed effects.
	pub fn dispatch(&mut self, ev: &Event) -> (Effects, Vec<Signal>) {
		let eff = kframe::inst_dispatch(&mut self.inst, ev);
		let sigs = self.decode_signals(&eff);
		(eff, sigs)
	}

	/// Drain solve-time signals queued by the most recent frame.
	pub fn take_signals(&mut self) -> (Effects, Vec<Signal>) {
		let eff = kframe::inst_take_signals(&mut self.inst);
		let sigs = self.decode_signals(&eff);
		(eff, sigs)
	}

	/// Decode Effects signal refs against the document's STRS pool.
	pub fn decode_signals(&self, eff: &Effects) -> Vec<Signal> {
		let mut out = Vec::new();
		for (i, &name) in eff.sig_name.iter().enumerate() {
			match name {
				SIG_SHUFFLE => out.push(Signal::Shuffle {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_PREV => out.push(Signal::Prev {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_TOGGLE => out.push(Signal::Toggle {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_NEXT => out.push(Signal::Next {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_LOOP => out.push(Signal::Loop {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				_ => {},
			}
		}
		out
	}

	/// Set param `title` (text); false = rejected by the kernel.
	pub fn set_title(&mut self, v: &str) -> bool {
		let pv = ParamValue::Text(v.to_string());
		kframe::inst_set_param(&mut self.inst, 0, &pv)
	}

	/// Set param `artist` (text); false = rejected by the kernel.
	pub fn set_artist(&mut self, v: &str) -> bool {
		let pv = ParamValue::Text(v.to_string());
		kframe::inst_set_param(&mut self.inst, 1, &pv)
	}

	/// Set param `elapsed` (text); false = rejected by the kernel.
	pub fn set_elapsed(&mut self, v: &str) -> bool {
		let pv = ParamValue::Text(v.to_string());
		kframe::inst_set_param(&mut self.inst, 2, &pv)
	}

	/// Set param `remain` (text); false = rejected by the kernel.
	pub fn set_remain(&mut self, v: &str) -> bool {
		let pv = ParamValue::Text(v.to_string());
		kframe::inst_set_param(&mut self.inst, 3, &pv)
	}

	/// Set param `progress` (pct (0..100)); false = rejected by the kernel.
	pub fn set_progress(&mut self, v: f64) -> bool {
		let pv = ParamValue::Pct(v);
		kframe::inst_set_param(&mut self.inst, 4, &pv)
	}

	/// Set param `playing` (bool); false = rejected by the kernel.
	pub fn set_playing(&mut self, v: bool) -> bool {
		let pv = ParamValue::Bool(v);
		kframe::inst_set_param(&mut self.inst, 5, &pv)
	}
}
