// GENERATED by `slab gen rust demos/vscode/vscode.slab` — do not edit.
// Regenerate: cargo run -q -p slab-cli -- gen rust demos/vscode/vscode.slab -o
// <this file> && cargo fmt
#![allow(
	clippy::derive_partial_eq_without_eq,
	clippy::use_self,
	clippy::doc_markdown,
	reason = "generated module favors uniform emission over per-document lint shape"
)]

use slab_kernel::{
	dispatch::{Effects, Event},
	flatten::Frame,
	frame::{self as kframe, HoleRect, Instance, ParamValue},
};
use slab_slir;

/// The compiled SLIR document (67451 bytes).
pub static SLIR: &[u8] = include_bytes!("gen_vscode.slir");

/// Packed SLIR color word (red in the low byte, then green, blue, alpha).
pub type Rgba = u32;

/// Pack straight-alpha RGBA channels for generated color params and list
/// fields.
pub const fn rgba(red: u8, green: u8, blue: u8, alpha: u8) -> Rgba {
	u32::from_le_bytes([red, green, blue, alpha])
}

/// Canonical full scene keys for authored `#id` nodes.
pub mod keys {
	pub const SIDEBAR: &str = "stack@0/col@0/row@1/#sidebar";
	pub const VIEWS: &str = "stack@0/col@0/row@1/#sidebar/#views";
	pub const VIEW_EXPLORER: &str = "stack@0/col@0/row@1/#sidebar/#views/#view-explorer";
	pub const TREESCROLL: &str = "stack@0/col@0/row@1/#sidebar/#views/#view-explorer/#treescroll";
	pub const TREEROWS: &str =
		"stack@0/col@0/row@1/#sidebar/#views/#view-explorer/#treescroll/#treerows";
	pub const VIEW_SEARCH: &str = "stack@0/col@0/row@1/#sidebar/#views/#view-search";
	pub const SEARCHROWS: &str = "stack@0/col@0/row@1/#sidebar/#views/#view-search/#searchrows";
	pub const VIEW_SCM: &str = "stack@0/col@0/row@1/#sidebar/#views/#view-scm";
	pub const SCMROWS: &str = "stack@0/col@0/row@1/#sidebar/#views/#view-scm/#scmrows";
	pub const VIEW_DEBUG: &str = "stack@0/col@0/row@1/#sidebar/#views/#view-debug";
	pub const VIEW_EXT: &str = "stack@0/col@0/row@1/#sidebar/#views/#view-ext";
	pub const EXTROWS: &str = "stack@0/col@0/row@1/#sidebar/#views/#view-ext/#extrows";
	pub const SASHL: &str = "stack@0/col@0/row@1/#sashL";
	pub const CENTER: &str = "stack@0/col@0/row@1/#center";
	pub const GRID: &str = "stack@0/col@0/row@1/#center/#grid";
	pub const EGROUPS: &str = "stack@0/col@0/row@1/#center/#grid/#egroups";
	pub const SASHP: &str = "stack@0/col@0/row@1/#center/#sashP";
	pub const PANEL: &str = "stack@0/col@0/row@1/#center/#panel";
	pub const PANELVIEWS: &str = "stack@0/col@0/row@1/#center/#panel/#panelviews";
	pub const PANEL_PROBLEMS: &str =
		"stack@0/col@0/row@1/#center/#panel/#panelviews/#panel-problems";
	pub const PROBLEMROWS: &str =
		"stack@0/col@0/row@1/#center/#panel/#panelviews/#panel-problems/#problemrows";
	pub const PANEL_OUTPUT: &str = "stack@0/col@0/row@1/#center/#panel/#panelviews/#panel-output";
	pub const PANEL_DEBUGC: &str = "stack@0/col@0/row@1/#center/#panel/#panelviews/#panel-debugc";
	pub const PANEL_TERMINAL: &str =
		"stack@0/col@0/row@1/#center/#panel/#panelviews/#panel-terminal";
	pub const PANEL_PORTS: &str = "stack@0/col@0/row@1/#center/#panel/#panelviews/#panel-ports";
	pub const SASHR: &str = "stack@0/col@0/row@1/#sashR";
	pub const CHAT: &str = "stack@0/col@0/row@1/#chat";
	pub const SESSIONROWS: &str = "stack@0/col@0/row@1/#chat/#sessionrows";
	pub const MENU: &str = "stack@0/#menu";
	pub const MENUITEMS: &str = "stack@0/#menu/#menuitems";
	pub const QUICKOPEN: &str = "stack@0/#quickopen";
	pub const QOROWS: &str = "stack@0/#quickopen/#qorows";
	pub const QOROWITEMS: &str = "stack@0/#quickopen/#qorows/#qorowitems";

	/// Join one `each` item into a full canonical scene key.
	///
	/// `item_key(EACH, item, "")` addresses the item root; a non-empty
	/// `rel` appends a template-relative key. `item` is escaped per the
	/// canonical grammar (`%` → `%25`, `/` → `%2F`, `~` → `%7E`).
	pub fn item_key(each: &str, item: &str, rel: &str) -> String {
		let mut escaped = String::with_capacity(item.len());
		for ch in item.chars() {
			match ch {
				'%' => escaped.push_str("%25"),
				'/' => escaped.push_str("%2F"),
				'~' => escaped.push_str("%7E"),
				_ => escaped.push(ch),
			}
		}
		if rel.is_empty() {
			format!("{each}~{escaped}")
		} else {
			format!("{each}~{escaped}/{rel}")
		}
	}

	/// Template-relative scene keys for the `treerows` each; join with
	/// [`item_key`].
	pub mod treerows {
		/// Canonical key of the each node itself.
		pub const EACH: &str =
			"stack@0/col@0/row@1/#sidebar/#views/#view-explorer/#treescroll/#treerows";
	}

	/// Template-relative scene keys for the `searchrows` each; join with
	/// [`item_key`].
	pub mod searchrows {
		/// Canonical key of the each node itself.
		pub const EACH: &str = "stack@0/col@0/row@1/#sidebar/#views/#view-search/#searchrows";
	}

	/// Template-relative scene keys for the `scmrows` each; join with
	/// [`item_key`].
	pub mod scmrows {
		/// Canonical key of the each node itself.
		pub const EACH: &str = "stack@0/col@0/row@1/#sidebar/#views/#view-scm/#scmrows";
	}

	/// Template-relative scene keys for the `extrows` each; join with
	/// [`item_key`].
	pub mod extrows {
		/// Canonical key of the each node itself.
		pub const EACH: &str = "stack@0/col@0/row@1/#sidebar/#views/#view-ext/#extrows";
	}

	/// Template-relative scene keys for the `egroups` each; join with
	/// [`item_key`].
	pub mod egroups {
		/// Canonical key of the each node itself.
		pub const EACH: &str = "stack@0/col@0/row@1/#center/#grid/#egroups";
		pub const PANES: &str = "stack@0/#panes";
		pub const KIDS: &str = "stack@0/#panes/#kids";
		pub const CHROME: &str = "stack@0/#chrome";
		pub const STRIP: &str = "stack@0/#chrome/row@0/#strip";
		pub const TABS: &str = "stack@0/#chrome/row@0/#strip/#tabs";
		pub const CRUMB: &str = "stack@0/#chrome/#crumb";
		pub const CRUMBSEACH: &str = "stack@0/#chrome/#crumb/#crumbseach";
		pub const ED: &str = "stack@0/#chrome/#ed";
		pub const CONTENT: &str = "stack@0/#chrome/#ed/#content";
		pub const EDSCROLL: &str = "stack@0/#chrome/#ed/#content/#edscroll";
		pub const CURLINE: &str = "stack@0/#chrome/#ed/#content/#edscroll/stack@0/col@0/#curline";
		pub const ZONE: &str = "stack@0/#chrome/#ed/#zone";
	}

	/// Template-relative scene keys for the `kids` each; join with [`item_key`].
	pub mod kids {
		/// Canonical key of the each node itself.
		pub const EACH: &str = "stack@0/#panes/#kids";
	}

	/// Template-relative scene keys for the `tabs` each; join with [`item_key`].
	pub mod tabs {
		/// Canonical key of the each node itself.
		pub const EACH: &str = "stack@0/#chrome/row@0/#strip/#tabs";
		pub const BODY: &str = "col@0/stack@0/#body";
		pub const INDL: &str = "col@0/stack@0/#indl";
		pub const INDR: &str = "col@0/stack@0/#indr";
	}

	/// Template-relative scene keys for the `crumbseach` each; join with
	/// [`item_key`].
	pub mod crumbseach {
		/// Canonical key of the each node itself.
		pub const EACH: &str = "stack@0/#chrome/#crumb/#crumbseach";
	}

	/// Template-relative scene keys for the `problemrows` each; join with
	/// [`item_key`].
	pub mod problemrows {
		/// Canonical key of the each node itself.
		pub const EACH: &str =
			"stack@0/col@0/row@1/#center/#panel/#panelviews/#panel-problems/#problemrows";
	}

	/// Template-relative scene keys for the `sessionrows` each; join with
	/// [`item_key`].
	pub mod sessionrows {
		/// Canonical key of the each node itself.
		pub const EACH: &str = "stack@0/col@0/row@1/#chat/#sessionrows";
	}

	/// Template-relative scene keys for the `menuitems` each; join with
	/// [`item_key`].
	pub mod menuitems {
		/// Canonical key of the each node itself.
		pub const EACH: &str = "stack@0/#menu/#menuitems";
	}

	/// Template-relative scene keys for the `qorowitems` each; join with
	/// [`item_key`].
	pub mod qorowitems {
		/// Canonical key of the each node itself.
		pub const EACH: &str = "stack@0/#quickopen/#qorows/#qorowitems";
	}
}

pub const PARAM_MENU_OPEN: u32 = 0;
pub const PARAM_MENU_ANCHOR: u32 = 1;
pub const PARAM_MENU_ITEMS: u32 = 2;
pub const PARAM_QO_OPEN: u32 = 3;
pub const PARAM_QO_SEL: u32 = 4;
pub const PARAM_QO_ROWS: u32 = 5;
pub const PARAM_ROOT: u32 = 6;
pub const PARAM_NAV_CANBACK: u32 = 7;
pub const PARAM_NAV_CANFWD: u32 = 8;
pub const PARAM_STATUS_LANG: u32 = 9;
pub const PARAM_STATUS_CARET: u32 = 10;
pub const PARAM_STATUS_ERRS: u32 = 11;
pub const PARAM_STATUS_WARNS: u32 = 12;
pub const PARAM_PANEL_PROBLEMS: u32 = 13;
pub const PARAM_PANEL_OUTPUT: u32 = 14;
pub const PARAM_PANEL_DEBUGC: u32 = 15;
pub const PARAM_PANEL_TERMINAL: u32 = 16;
pub const PARAM_PANEL_PORTS: u32 = 17;
pub const PARAM_PANEL_TERMLOG: u32 = 18;
pub const PARAM_TREE: u32 = 19;
pub const PARAM_SCM_CHANGES: u32 = 20;
pub const PARAM_CHAT_SESSIONS: u32 = 21;
pub const PARAM_CHAT_TYPING: u32 = 22;
pub const PARAM_PROBLEMS_FILTERING: u32 = 23;
pub const PARAM_PROBLEMS_ROWS: u32 = 24;
pub const PARAM_SIDEBAR_EXPLORER: u32 = 25;
pub const PARAM_SIDEBAR_SEARCH: u32 = 26;
pub const PARAM_SIDEBAR_SCM: u32 = 27;
pub const PARAM_SIDEBAR_DEBUG: u32 = 28;
pub const PARAM_SIDEBAR_EXT: u32 = 29;
pub const PARAM_SEARCH_RESULTS: u32 = 30;
pub const PARAM_EXT_ROWS: u32 = 31;
const SIG_NAV_BACK: u32 = 52;
const SIG_NAV_FWD: u32 = 60;
const SIG_ACTIVITY_PICK: u32 = 93;
const SIG_TREE_PICK: u32 = 153;
const SIG_SIDEBAR_SEARCH_CHANGE: u32 = 185;
const SIG_SEARCH_PICK: u32 = 192;
const SIG_SCM_PICK: u32 = 215;
const SIG_EXT_SEARCH_CHANGE: u32 = 239;
const SIG_SASH_SIDEBAR: u32 = 250;
const SIG_SPLIT_RESIZE: u32 = 260;
const SIG_STRIP_DBL: u32 = 271;
const SIG_STRIP_DROP: u32 = 270;
const SIG_TAB_PRESS: u32 = 278;
const SIG_TAB_MENU: u32 = 282;
const SIG_TAB_DBL: u32 = 280;
const SIG_TAB_DRAG: u32 = 283;
const SIG_TAB_DROP: u32 = 281;
const SIG_TAB_UP: u32 = 279;
const SIG_TAB_MOVE: u32 = 284;
const SIG_TAB_END: u32 = 285;
const SIG_TAB_CLOSE: u32 = 295;
const SIG_EDITOR_DROP: u32 = 320;
const SIG_CODE_CHANGE: u32 = 334;
const SIG_FIND_CHANGE: u32 = 347;
const SIG_FIND_SUBMIT: u32 = 348;
const SIG_FIND_CLOSE: u32 = 364;
const SIG_SASH_PANEL: u32 = 369;
const SIG_PANEL_PICK: u32 = 374;
const SIG_PROBLEMS_FILTER_CHANGE: u32 = 399;
const SIG_PANEL_MAX: u32 = 407;
const SIG_PANEL_CLOSE: u32 = 410;
const SIG_PROBLEM_PICK: u32 = 418;
const SIG_TERM_CHANGE: u32 = 447;
const SIG_TERM_SEND: u32 = 448;
const SIG_SASH_CENTER: u32 = 459;
const SIG_CHAT_CHANGE: u32 = 507;
const SIG_CHAT_SEND: u32 = 508;
const SIG_STATUS_PROBLEMS: u32 = 539;
const SIG_MENU_PICK: u32 = 594;
const SIG_QO_CHANGE: u32 = 602;
const SIG_QO_PICK: u32 = 608;

/// Metadata captured for every emitted signal.
#[derive(Debug, Clone, PartialEq)]
pub struct SignalMeta {
	/// Document-space pointer x, or `-1.0` for keyboard origin.
	pub x:           f64,
	/// Document-space pointer y, or `-1.0` for keyboard origin.
	pub y:           f64,
	/// Horizontal delta carried by the originating event.
	pub dx:          f64,
	/// Vertical delta carried by the originating event.
	pub dy:          f64,
	/// Horizontal drag displacement from the pointer-down origin.
	pub drag_dx:     f64,
	/// Vertical drag displacement from the pointer-down origin.
	pub drag_dy:     f64,
	/// Modifier bitset active at emission.
	pub mods:        u32,
	/// Pointer button code.
	pub button:      u32,
	/// Host-computed click count.
	pub clicks:      u32,
	/// Full key path of the signal-emitting node.
	pub key:         String,
	/// Full drag-source key for Drop, otherwise empty.
	pub src_key:     String,
	/// Innermost drag-source item key for `Drop`, otherwise empty.
	pub src_item:    String,
	/// Whether `DragEnd` represents abnormal termination.
	pub cancelled:   bool,
	/// Whether `DragEnd` delivered `Drop` to an eligible target.
	pub dropped:     bool,
	/// Deepest hit-target key on pointer-derived signals, otherwise empty.
	pub hit_key:     String,
	/// Pressed key name on keyboard-driven activation, otherwise empty.
	pub pressed_key: String,
}

impl From<&slab_kernel::dispatch::SigMeta> for SignalMeta {
	fn from(meta: &slab_kernel::dispatch::SigMeta) -> Self {
		Self {
			x:           meta.x,
			y:           meta.y,
			dx:          meta.dx,
			dy:          meta.dy,
			drag_dx:     meta.drag_dx,
			drag_dy:     meta.drag_dy,
			mods:        meta.mods,
			button:      meta.button,
			clicks:      meta.clicks,
			key:         meta.key.clone(),
			src_key:     meta.src_key.clone(),
			src_item:    meta.src_item.clone(),
			cancelled:   meta.cancelled,
			dropped:     meta.dropped,
			hit_key:     meta.hit_key.clone(),
			pressed_key: meta.pressed_key.clone(),
		}
	}
}

/// Signals declared in the document's SIGN table.
#[derive(Debug, Clone, PartialEq)]
pub enum Signal {
	/// A signal carrying list identity and input metadata.
	NavBack {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	NavFwd {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	ActivityPick {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	TreePick {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A text-bearing signal with list identity and input metadata.
	SidebarSearchChange {
		/// Committed field text or final resize extent.
		text: String,
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	SearchPick {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	ScmPick {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A text-bearing signal with list identity and input metadata.
	ExtSearchChange {
		/// Committed field text or final resize extent.
		text: String,
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A text-bearing signal with list identity and input metadata.
	SashSidebar {
		/// Committed field text or final resize extent.
		text: String,
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A text-bearing signal with list identity and input metadata.
	SplitResize {
		/// Committed field text or final resize extent.
		text: String,
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	StripDbl {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	StripDrop {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	TabPress {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	TabMenu {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	TabDbl {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	TabDrag {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	TabDrop {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	TabUp {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	TabMove {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	TabEnd {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	TabClose {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	EditorDrop {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A text-bearing signal with list identity and input metadata.
	CodeChange {
		/// Committed field text or final resize extent.
		text: String,
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A text-bearing signal with list identity and input metadata.
	FindChange {
		/// Committed field text or final resize extent.
		text: String,
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A text-bearing signal with list identity and input metadata.
	FindSubmit {
		/// Committed field text or final resize extent.
		text: String,
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	FindClose {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A text-bearing signal with list identity and input metadata.
	SashPanel {
		/// Committed field text or final resize extent.
		text: String,
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	PanelPick {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A text-bearing signal with list identity and input metadata.
	ProblemsFilterChange {
		/// Committed field text or final resize extent.
		text: String,
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	PanelMax {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	PanelClose {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	ProblemPick {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A text-bearing signal with list identity and input metadata.
	TermChange {
		/// Committed field text or final resize extent.
		text: String,
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A text-bearing signal with list identity and input metadata.
	TermSend {
		/// Committed field text or final resize extent.
		text: String,
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A text-bearing signal with list identity and input metadata.
	SashCenter {
		/// Committed field text or final resize extent.
		text: String,
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A text-bearing signal with list identity and input metadata.
	ChatChange {
		/// Committed field text or final resize extent.
		text: String,
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A text-bearing signal with list identity and input metadata.
	ChatSend {
		/// Committed field text or final resize extent.
		text: String,
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	StatusProblems {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	MenuPick {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A text-bearing signal with list identity and input metadata.
	QoChange {
		/// Committed field text or final resize extent.
		text: String,
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
	/// A signal carrying list identity and input metadata.
	QoPick {
		/// Innermost list item key, or empty outside a list.
		item: String,
		/// Input and source metadata.
		meta: SignalMeta,
	},
}

/// Names accepted by the document's signal surface.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub enum SignalName {
	NavBack,
	NavFwd,
	ActivityPick,
	TreePick,
	SidebarSearchChange,
	SearchPick,
	ScmPick,
	ExtSearchChange,
	SashSidebar,
	SplitResize,
	StripDbl,
	StripDrop,
	TabPress,
	TabMenu,
	TabDbl,
	TabDrag,
	TabDrop,
	TabUp,
	TabMove,
	TabEnd,
	TabClose,
	EditorDrop,
	CodeChange,
	FindChange,
	FindSubmit,
	FindClose,
	SashPanel,
	PanelPick,
	ProblemsFilterChange,
	PanelMax,
	PanelClose,
	ProblemPick,
	TermChange,
	TermSend,
	SashCenter,
	ChatChange,
	ChatSend,
	StatusProblems,
	MenuPick,
	QoChange,
	QoPick,
}

impl SignalName {
	/// Return the authored signal name.
	pub const fn as_str(self) -> &'static str {
		match self {
			Self::NavBack => "nav_back",
			Self::NavFwd => "nav_fwd",
			Self::ActivityPick => "activity_pick",
			Self::TreePick => "tree_pick",
			Self::SidebarSearchChange => "sidebar_search_change",
			Self::SearchPick => "search_pick",
			Self::ScmPick => "scm_pick",
			Self::ExtSearchChange => "ext_search_change",
			Self::SashSidebar => "sash_sidebar",
			Self::SplitResize => "split_resize",
			Self::StripDbl => "strip_dbl",
			Self::StripDrop => "strip_drop",
			Self::TabPress => "tab_press",
			Self::TabMenu => "tab_menu",
			Self::TabDbl => "tab_dbl",
			Self::TabDrag => "tab_drag",
			Self::TabDrop => "tab_drop",
			Self::TabUp => "tab_up",
			Self::TabMove => "tab_move",
			Self::TabEnd => "tab_end",
			Self::TabClose => "tab_close",
			Self::EditorDrop => "editor_drop",
			Self::CodeChange => "code_change",
			Self::FindChange => "find_change",
			Self::FindSubmit => "find_submit",
			Self::FindClose => "find_close",
			Self::SashPanel => "sash_panel",
			Self::PanelPick => "panel_pick",
			Self::ProblemsFilterChange => "problems_filter_change",
			Self::PanelMax => "panel_max",
			Self::PanelClose => "panel_close",
			Self::ProblemPick => "problem_pick",
			Self::TermChange => "term_change",
			Self::TermSend => "term_send",
			Self::SashCenter => "sash_center",
			Self::ChatChange => "chat_change",
			Self::ChatSend => "chat_send",
			Self::StatusProblems => "status_problems",
			Self::MenuPick => "menu_pick",
			Self::QoChange => "qo_change",
			Self::QoPick => "qo_pick",
		}
	}
}

/// One typed item accepted by [`Doc::set_menu_items`] for list param
/// `menu.items`.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct MenuItemsItem {
	/// Stable item key; `None` uses the current positional key.
	pub key:     Option<String>,
	/// Schema field `label` (text).
	pub label:   String,
	/// Schema field `enabled` (boolean).
	pub enabled: bool,
}

impl MenuItemsItem {
	/// Attach a stable list identity; omit this call to use the positional key.
	pub fn with_key(mut self, key: impl Into<String>) -> Self {
		self.key = Some(key.into());
		self
	}
}

/// One typed item accepted by [`Doc::set_qo_rows`] for list param `qo.rows`.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct QoRowsItem {
	/// Stable item key; `None` uses the current positional key.
	pub key:      Option<String>,
	/// Schema field `name` (text).
	pub name:     String,
	/// Schema field `dir` (text).
	pub dir:      String,
	/// Schema field `letter` (text).
	pub letter:   String,
	/// Schema field `selected` (boolean).
	pub selected: bool,
}

impl QoRowsItem {
	/// Attach a stable list identity; omit this call to use the positional key.
	pub fn with_key(mut self, key: impl Into<String>) -> Self {
		self.key = Some(key.into());
		self
	}
}

/// One typed item accepted by [`Doc::set_root`] for list param `root`.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct RootItem {
	/// Stable item key; `None` uses the current positional key.
	pub key:         Option<String>,
	/// Schema field `leaf` (boolean).
	pub leaf:        bool,
	/// Schema field `horizontal` (boolean).
	pub horizontal:  bool,
	/// Schema field `show_mdb` (boolean).
	pub show_mdb:    bool,
	/// Schema field `show_store` (boolean).
	pub show_store:  bool,
	/// Schema field `show_edit` (boolean).
	pub show_edit:   bool,
	/// Schema field `show_find` (boolean).
	pub show_find:   bool,
	/// Schema field `find_status` (text).
	pub find_status: String,
	/// Schema field `curline` (number).
	pub curline:     f64,
	/// Schema field `curline_on` (boolean).
	pub curline_on:  bool,
	/// Schema field `gutter` (text).
	pub gutter:      String,
	/// Schema field `crumbs` (nested list).
	pub crumbs:      Vec<RootCrumbsItem>,
	/// Schema field `tabs` (nested list).
	pub tabs:        Vec<RootTabsItem>,
	/// Schema field `children` (nested list).
	pub children:    Vec<RootItem>,
}

impl RootItem {
	/// Attach a stable list identity; omit this call to use the positional key.
	pub fn with_key(mut self, key: impl Into<String>) -> Self {
		self.key = Some(key.into());
		self
	}
}

/// One typed nested-list item reachable from list param `root`.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct RootCrumbsItem {
	/// Stable item key; `None` uses the current positional key.
	pub key:    Option<String>,
	/// Schema field `seg` (text).
	pub seg:    String,
	/// Schema field `letter` (text).
	pub letter: String,
	/// Schema field `last` (boolean).
	pub last:   bool,
}

impl RootCrumbsItem {
	/// Attach a stable list identity; omit this call to use the positional key.
	pub fn with_key(mut self, key: impl Into<String>) -> Self {
		self.key = Some(key.into());
		self
	}
}

/// One typed nested-list item reachable from list param `root`.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct RootTabsItem {
	/// Stable item key; `None` uses the current positional key.
	pub key:     Option<String>,
	/// Schema field `name` (text).
	pub name:    String,
	/// Schema field `note` (text).
	pub note:    String,
	/// Schema field `tint` (packed SLIR RGBA color).
	pub tint:    Rgba,
	/// Schema field `badge` (text).
	pub badge:   String,
	/// Schema field `active` (boolean).
	pub active:  bool,
	/// Schema field `hot` (boolean).
	pub hot:     bool,
	/// Schema field `preview` (boolean).
	pub preview: bool,
	/// Schema field `dirty` (boolean).
	pub dirty:   bool,
}

impl RootTabsItem {
	/// Attach a stable list identity; omit this call to use the positional key.
	pub fn with_key(mut self, key: impl Into<String>) -> Self {
		self.key = Some(key.into());
		self
	}
}

/// One typed item accepted by [`Doc::set_tree`] for list param `tree`.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct TreeItem {
	/// Stable item key; `None` uses the current positional key.
	pub key:    Option<String>,
	/// Schema field `name` (text).
	pub name:   String,
	/// Schema field `letter` (text).
	pub letter: String,
	/// Schema field `icon` (text).
	pub icon:   String,
	/// Schema field `tint` (packed SLIR RGBA color).
	pub tint:   Rgba,
	/// Schema field `badge` (text).
	pub badge:  String,
	/// Schema field `indent` (number).
	pub indent: f64,
	/// Schema field `dir` (boolean).
	pub dir:    bool,
	/// Schema field `open` (boolean).
	pub open:   bool,
}

impl TreeItem {
	/// Attach a stable list identity; omit this call to use the positional key.
	pub fn with_key(mut self, key: impl Into<String>) -> Self {
		self.key = Some(key.into());
		self
	}
}

/// One typed item accepted by [`Doc::set_scm_changes`] for list param
/// `scm.changes`.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ScmChangesItem {
	/// Stable item key; `None` uses the current positional key.
	pub key:   Option<String>,
	/// Schema field `file` (text).
	pub file:  String,
	/// Schema field `badge` (text).
	pub badge: String,
}

impl ScmChangesItem {
	/// Attach a stable list identity; omit this call to use the positional key.
	pub fn with_key(mut self, key: impl Into<String>) -> Self {
		self.key = Some(key.into());
		self
	}
}

/// One typed item accepted by [`Doc::set_chat_sessions`] for list param
/// `chat.sessions`.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ChatSessionsItem {
	/// Stable item key; `None` uses the current positional key.
	pub key:   Option<String>,
	/// Schema field `title` (text).
	pub title: String,
}

impl ChatSessionsItem {
	/// Attach a stable list identity; omit this call to use the positional key.
	pub fn with_key(mut self, key: impl Into<String>) -> Self {
		self.key = Some(key.into());
		self
	}
}

/// One typed item accepted by [`Doc::set_problems_rows`] for list param
/// `problems.rows`.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ProblemsRowsItem {
	/// Stable item key; `None` uses the current positional key.
	pub key:  Option<String>,
	/// Schema field `icon` (text).
	pub icon: String,
	/// Schema field `file` (text).
	pub file: String,
	/// Schema field `line` (text).
	pub line: String,
	/// Schema field `msg` (text).
	pub msg:  String,
	/// Schema field `tint` (packed SLIR RGBA color).
	pub tint: Rgba,
}

impl ProblemsRowsItem {
	/// Attach a stable list identity; omit this call to use the positional key.
	pub fn with_key(mut self, key: impl Into<String>) -> Self {
		self.key = Some(key.into());
		self
	}
}

/// One typed item accepted by [`Doc::set_search_results`] for list param
/// `search.results`.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct SearchResultsItem {
	/// Stable item key; `None` uses the current positional key.
	pub key:     Option<String>,
	/// Schema field `file` (text).
	pub file:    String,
	/// Schema field `line` (text).
	pub line:    String,
	/// Schema field `preview` (text).
	pub preview: String,
}

impl SearchResultsItem {
	/// Attach a stable list identity; omit this call to use the positional key.
	pub fn with_key(mut self, key: impl Into<String>) -> Self {
		self.key = Some(key.into());
		self
	}
}

/// One typed item accepted by [`Doc::set_ext_rows`] for list param `ext.rows`.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ExtRowsItem {
	/// Stable item key; `None` uses the current positional key.
	pub key:       Option<String>,
	/// Schema field `name` (text).
	pub name:      String,
	/// Schema field `publisher` (text).
	pub publisher: String,
}

impl ExtRowsItem {
	/// Attach a stable list identity; omit this call to use the positional key.
	pub fn with_key(mut self, key: impl Into<String>) -> Self {
		self.key = Some(key.into());
		self
	}
}

/// The document instance, driven through `slab-kernel`.
pub struct Doc {
	/// Raw kernel instance for advanced integrations.
	pub inst:             Instance,
	/// Image bytes carried by the compiled document.
	pub imgs:             Vec<Vec<u8>>,
	menu_items_cache:     Option<Vec<MenuItemsItem>>,
	qo_rows_cache:        Option<Vec<QoRowsItem>>,
	root_cache:           Option<Vec<RootItem>>,
	tree_cache:           Option<Vec<TreeItem>>,
	scm_changes_cache:    Option<Vec<ScmChangesItem>>,
	chat_sessions_cache:  Option<Vec<ChatSessionsItem>>,
	problems_rows_cache:  Option<Vec<ProblemsRowsItem>>,
	search_results_cache: Option<Vec<SearchResultsItem>>,
	ext_rows_cache:       Option<Vec<ExtRowsItem>>,
}

impl Default for Doc {
	fn default() -> Self {
		Self::new()
	}
}

impl Doc {
	/// Create an instance initialized from the included document.
	pub fn new() -> Self {
		let (doc, imgs) = slab_slir::decode_doc(SLIR).expect("included SLIR");
		let inst = kframe::inst_from_doc(doc);
		Self {
			inst,
			imgs,
			menu_items_cache: None,
			qo_rows_cache: None,
			root_cache: None,
			tree_cache: None,
			scm_changes_cache: None,
			chat_sessions_cache: None,
			problems_rows_cache: None,
			search_results_cache: None,
			ext_rows_cache: None,
		}
	}

	/// Whether the included document decoded successfully.
	pub const fn ok(&self) -> bool {
		self.inst.ok
	}

	/// Env for the gpu client (client code 1); portrait derives from vw < vh.
	pub fn set_env(&mut self, vw: f64, vh: f64, dark: bool, coarse: bool) {
		kframe::inst_set_env(&mut self.inst, vw, vh, 1, dark, coarse);
	}

	/// Select a compiler-declared theme; an empty name restores authored values.
	pub fn set_theme(&mut self, name: &str) -> bool {
		kframe::inst_set_theme(&mut self.inst, name)
	}

	/// Drop generated list reconciliation snapshots after an external document
	/// reload. Call this when a host-mounted `RequestPump` reports `reloaded ==
	/// true`, before re-synchronizing typed list setters. Safe and idempotent.
	#[allow(
		clippy::missing_const_for_fn,
		reason = "documents without list params leave this body empty"
	)]
	pub fn invalidate_caches(&mut self) {
		self.menu_items_cache = None;
		self.qo_rows_cache = None;
		self.root_cache = None;
		self.tree_cache = None;
		self.scm_changes_cache = None;
		self.chat_sessions_cache = None;
		self.problems_rows_cache = None;
		self.search_results_cache = None;
		self.ext_rows_cache = None;
	}

	/// Read one token resolved through the active theme, with base fallback.
	pub fn get_token(&self, path: &str) -> Option<kframe::TokenValue<'_>> {
		kframe::inst_get_token(&self.inst, path)
	}

	/// Move focus to a keyed focusable node; an empty key clears focus.
	/// `visible` shows the keyboard-grade focus ring.
	pub fn set_focus(&mut self, key: &str, visible: bool) -> bool {
		kframe::inst_set_focus(&mut self.inst, key, visible)
	}

	/// Clear focus while retaining field edit buffers.
	pub fn clear_focus(&mut self) -> bool {
		kframe::inst_clear_focus(&mut self.inst)
	}

	/// Focus and reveal a concrete item in an `each` list.
	pub fn focus_item(&mut self, each_key: &str, index: i32) -> bool {
		kframe::inst_focus_item(&mut self.inst, each_key, index)
	}

	/// Explain the most recent failed focus operation.
	pub fn focus_note(&self) -> &str {
		kframe::inst_focus_note(&self.inst)
	}

	/// Replace a keyed field buffer, reset its edit history, and emit Change.
	pub fn set_field_text(&mut self, key: &str, text: &str) -> bool {
		kframe::inst_set_field_text(&mut self.inst, key, text)
	}

	/// Return a keyed field's committed text, or `None` for a non-field key.
	pub fn field_text(&self, key: &str) -> Option<String> {
		kframe::inst_field_text(&self.inst, key)
	}

	/// Current theme name; empty means the authored base.
	pub fn theme(&self) -> String {
		kframe::inst_theme(&self.inst)
	}

	/// Solve and flatten the document at `t_ms` milliseconds.
	pub fn frame(&mut self, t_ms: f64) -> Frame {
		kframe::inst_frame(&mut self.inst, t_ms)
	}

	/// Return the current host-content hole rectangles.
	pub fn holes(&mut self) -> Vec<HoleRect> {
		kframe::inst_holes(&mut self.inst)
	}

	/// Set a keyed scroll node's offset on axis 0 (main) or 1 (cross).
	pub fn set_scroll(&mut self, key: &str, axis: u32, off: f64) -> bool {
		kframe::inst_set_scroll(&mut self.inst, key, axis, off)
	}

	/// Read a keyed scroll node's offset on axis 0 (main) or 1 (cross).
	pub fn get_scroll(&self, key: &str, axis: u32) -> f64 {
		kframe::inst_get_scroll(&self.inst, key, axis)
	}

	/// Register or replace a named runtime image and return its unified image
	/// index.
	pub fn img_register(&mut self, name: &str, w: u32, h: u32, format: u32, data: &[u8]) -> i32 {
		kframe::inst_img_register(&mut self.inst, name, w, h, format, data)
	}

	/// Unregister a named runtime image while preserving its unified image
	/// index.
	pub fn img_unregister(&mut self, name: &str) -> bool {
		kframe::inst_img_unregister(&mut self.inst, name)
	}

	/// Scroll ancestors minimally to reveal a keyed node with the requested
	/// margin.
	pub fn reveal(&mut self, key: &str, margin: f64) -> bool {
		kframe::inst_reveal(&mut self.inst, key, margin)
	}

	/// Reveal an item in a virtual list using start, center, end, or nearest
	/// alignment.
	pub fn reveal_item(&mut self, each_key: &str, index: i32, align: u32) -> bool {
		kframe::inst_reveal_item(&mut self.inst, each_key, index, align)
	}

	/// Return a virtual list's materialized half-open item window.
	pub fn each_window(&self, each_key: &str) -> (i32, i32) {
		kframe::inst_each_window(&self.inst, each_key)
	}

	/// Enable retained per-item extents and update one virtual-list item.
	pub fn set_item_extent(&mut self, each_key: &str, index: i32, extent: f64) -> bool {
		kframe::inst_set_item_extent(&mut self.inst, each_key, index, extent)
	}

	/// Set the extent overlay controlled by a keyed divider.
	pub fn set_divider(&mut self, key: &str, extent: f64) -> bool {
		kframe::inst_set_divider(&mut self.inst, key, extent)
	}

	/// Read a keyed divider's extent overlay, or `-1.0` when unknown or unset.
	pub fn get_divider(&self, key: &str) -> f64 {
		kframe::inst_get_divider(&self.inst, key)
	}

	/// Set one retained split-pane size.
	pub fn set_split(&mut self, pane_key: &str, size: f64) -> bool {
		kframe::inst_set_split(&mut self.inst, pane_key, size)
	}

	/// Read one retained split-pane size, or `-1.0` when unknown.
	pub fn get_split(&self, pane_key: &str) -> f64 {
		kframe::inst_get_split(&self.inst, pane_key)
	}

	/// Dispatch an input event and return its raw and typed effects.
	pub fn dispatch(&mut self, ev: &Event) -> (Effects, Vec<Signal>) {
		let eff = kframe::inst_dispatch(&mut self.inst, ev);
		let sigs = self.decode_signals(&eff);
		(eff, sigs)
	}

	/// Drain solve-time signals queued by the most recent frame.
	pub fn take_signals(&mut self) -> (Effects, Vec<Signal>) {
		let eff = kframe::inst_take_signals(&mut self.inst);
		let sigs = self.decode_signals(&eff);
		(eff, sigs)
	}

	/// Decode Effects signal refs against the document's STRS pool.
	pub fn decode_signals(&self, eff: &Effects) -> Vec<Signal> {
		let mut out = Vec::new();
		for (i, &name) in eff.sig_name.iter().enumerate() {
			match name {
				SIG_NAV_BACK => out.push(Signal::NavBack {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_NAV_FWD => out.push(Signal::NavFwd {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_ACTIVITY_PICK => out.push(Signal::ActivityPick {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_TREE_PICK => out.push(Signal::TreePick {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_SIDEBAR_SEARCH_CHANGE => out.push(Signal::SidebarSearchChange {
					text: eff.sig_text[i].clone(),
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_SEARCH_PICK => out.push(Signal::SearchPick {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_SCM_PICK => out.push(Signal::ScmPick {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_EXT_SEARCH_CHANGE => out.push(Signal::ExtSearchChange {
					text: eff.sig_text[i].clone(),
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_SASH_SIDEBAR => out.push(Signal::SashSidebar {
					text: eff.sig_text[i].clone(),
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_SPLIT_RESIZE => out.push(Signal::SplitResize {
					text: eff.sig_text[i].clone(),
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_STRIP_DBL => out.push(Signal::StripDbl {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_STRIP_DROP => out.push(Signal::StripDrop {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_TAB_PRESS => out.push(Signal::TabPress {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_TAB_MENU => out.push(Signal::TabMenu {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_TAB_DBL => out.push(Signal::TabDbl {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_TAB_DRAG => out.push(Signal::TabDrag {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_TAB_DROP => out.push(Signal::TabDrop {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_TAB_UP => out.push(Signal::TabUp {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_TAB_MOVE => out.push(Signal::TabMove {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_TAB_END => out.push(Signal::TabEnd {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_TAB_CLOSE => out.push(Signal::TabClose {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_EDITOR_DROP => out.push(Signal::EditorDrop {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_CODE_CHANGE => out.push(Signal::CodeChange {
					text: eff.sig_text[i].clone(),
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_FIND_CHANGE => out.push(Signal::FindChange {
					text: eff.sig_text[i].clone(),
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_FIND_SUBMIT => out.push(Signal::FindSubmit {
					text: eff.sig_text[i].clone(),
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_FIND_CLOSE => out.push(Signal::FindClose {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_SASH_PANEL => out.push(Signal::SashPanel {
					text: eff.sig_text[i].clone(),
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_PANEL_PICK => out.push(Signal::PanelPick {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_PROBLEMS_FILTER_CHANGE => out.push(Signal::ProblemsFilterChange {
					text: eff.sig_text[i].clone(),
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_PANEL_MAX => out.push(Signal::PanelMax {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_PANEL_CLOSE => out.push(Signal::PanelClose {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_PROBLEM_PICK => out.push(Signal::ProblemPick {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_TERM_CHANGE => out.push(Signal::TermChange {
					text: eff.sig_text[i].clone(),
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_TERM_SEND => out.push(Signal::TermSend {
					text: eff.sig_text[i].clone(),
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_SASH_CENTER => out.push(Signal::SashCenter {
					text: eff.sig_text[i].clone(),
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_CHAT_CHANGE => out.push(Signal::ChatChange {
					text: eff.sig_text[i].clone(),
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_CHAT_SEND => out.push(Signal::ChatSend {
					text: eff.sig_text[i].clone(),
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_STATUS_PROBLEMS => out.push(Signal::StatusProblems {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_MENU_PICK => out.push(Signal::MenuPick {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_QO_CHANGE => out.push(Signal::QoChange {
					text: eff.sig_text[i].clone(),
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				SIG_QO_PICK => out.push(Signal::QoPick {
					item: eff.sig_item[i].clone(),
					meta: SignalMeta::from(&eff.sig_meta[i]),
				}),
				_ => {},
			}
		}
		out
	}

	fn validate_menuitems(items: &[MenuItemsItem]) -> bool {
		let Ok(_) = i32::try_from(items.len()) else {
			return false;
		};
		let mut keys = std::collections::HashSet::with_capacity(items.len());
		for (index, item) in items.iter().enumerate() {
			let key = item.key.clone().unwrap_or_else(|| index.to_string());
			if key.is_empty() || !keys.insert(key) {
				return false;
			}
		}
		true
	}

	fn set_menuitems_path(
		&mut self,
		path: &str,
		items: &[MenuItemsItem],
		previous: Option<&[MenuItemsItem]>,
	) -> bool {
		let Ok(len) = i32::try_from(items.len()) else {
			return false;
		};
		if !kframe::inst_set_list_len(&mut self.inst, 2, path, len) {
			return false;
		}
		for (item_index, item) in items.iter().enumerate() {
			let previous = previous.and_then(|items| items.get(item_index));
			if previous == Some(item) {
				continue;
			}
			let Ok(index) = i32::try_from(item_index) else {
				return false;
			};
			if previous.is_none_or(|previous| previous.key != item.key) {
				let key = item.key.clone().unwrap_or_else(|| item_index.to_string());
				if !kframe::inst_set_list_key(&mut self.inst, 2, path, index, &key) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.label != item.label) {
				let pv = ParamValue::Text(item.label.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 2, path, index, "label", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.enabled != item.enabled) {
				let pv = ParamValue::Bool(item.enabled);
				if !kframe::inst_set_list_field(&mut self.inst, 2, path, index, "enabled", &pv) {
					return false;
				}
			}
		}
		true
	}

	/// Reconciles list param `menu.items` and all nested lists with the last
	/// typed value.
	pub fn set_menu_items(&mut self, items: &[MenuItemsItem]) -> bool {
		if self.menu_items_cache.as_deref() == Some(items) {
			return true;
		}
		if !Self::validate_menuitems(items) {
			return false;
		}
		let previous = self.menu_items_cache.take();
		let updated = self.set_menuitems_path("", items, previous.as_deref());
		self.menu_items_cache = if updated {
			Some(items.to_vec())
		} else {
			previous
		};
		updated
	}

	fn validate_qorows(items: &[QoRowsItem]) -> bool {
		let Ok(_) = i32::try_from(items.len()) else {
			return false;
		};
		let mut keys = std::collections::HashSet::with_capacity(items.len());
		for (index, item) in items.iter().enumerate() {
			let key = item.key.clone().unwrap_or_else(|| index.to_string());
			if key.is_empty() || !keys.insert(key) {
				return false;
			}
		}
		true
	}

	fn set_qorows_path(
		&mut self,
		path: &str,
		items: &[QoRowsItem],
		previous: Option<&[QoRowsItem]>,
	) -> bool {
		let Ok(len) = i32::try_from(items.len()) else {
			return false;
		};
		if !kframe::inst_set_list_len(&mut self.inst, 5, path, len) {
			return false;
		}
		for (item_index, item) in items.iter().enumerate() {
			let previous = previous.and_then(|items| items.get(item_index));
			if previous == Some(item) {
				continue;
			}
			let Ok(index) = i32::try_from(item_index) else {
				return false;
			};
			if previous.is_none_or(|previous| previous.key != item.key) {
				let key = item.key.clone().unwrap_or_else(|| item_index.to_string());
				if !kframe::inst_set_list_key(&mut self.inst, 5, path, index, &key) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.name != item.name) {
				let pv = ParamValue::Text(item.name.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 5, path, index, "name", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.dir != item.dir) {
				let pv = ParamValue::Text(item.dir.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 5, path, index, "dir", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.letter != item.letter) {
				let pv = ParamValue::Text(item.letter.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 5, path, index, "letter", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.selected != item.selected) {
				let pv = ParamValue::Bool(item.selected);
				if !kframe::inst_set_list_field(&mut self.inst, 5, path, index, "selected", &pv) {
					return false;
				}
			}
		}
		true
	}

	/// Reconciles list param `qo.rows` and all nested lists with the last typed
	/// value.
	pub fn set_qo_rows(&mut self, items: &[QoRowsItem]) -> bool {
		if self.qo_rows_cache.as_deref() == Some(items) {
			return true;
		}
		if !Self::validate_qorows(items) {
			return false;
		}
		let previous = self.qo_rows_cache.take();
		let updated = self.set_qorows_path("", items, previous.as_deref());
		self.qo_rows_cache = if updated {
			Some(items.to_vec())
		} else {
			previous
		};
		updated
	}

	fn validate_root(items: &[RootItem]) -> bool {
		let Ok(_) = i32::try_from(items.len()) else {
			return false;
		};
		let mut keys = std::collections::HashSet::with_capacity(items.len());
		for (index, item) in items.iter().enumerate() {
			let key = item.key.clone().unwrap_or_else(|| index.to_string());
			if key.is_empty() || !keys.insert(key) {
				return false;
			}
			if !Self::validate_rootcrumbs(&item.crumbs) {
				return false;
			}
			if !Self::validate_roottabs(&item.tabs) {
				return false;
			}
			if !Self::validate_root(&item.children) {
				return false;
			}
		}
		true
	}

	fn set_root_path(
		&mut self,
		path: &str,
		items: &[RootItem],
		previous: Option<&[RootItem]>,
	) -> bool {
		let Ok(len) = i32::try_from(items.len()) else {
			return false;
		};
		if !kframe::inst_set_list_len(&mut self.inst, 6, path, len) {
			return false;
		}
		for (item_index, item) in items.iter().enumerate() {
			let previous = previous.and_then(|items| items.get(item_index));
			if previous == Some(item) {
				continue;
			}
			let Ok(index) = i32::try_from(item_index) else {
				return false;
			};
			if previous.is_none_or(|previous| previous.key != item.key) {
				let key = item.key.clone().unwrap_or_else(|| item_index.to_string());
				if !kframe::inst_set_list_key(&mut self.inst, 6, path, index, &key) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.leaf != item.leaf) {
				let pv = ParamValue::Bool(item.leaf);
				if !kframe::inst_set_list_field(&mut self.inst, 6, path, index, "leaf", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.horizontal != item.horizontal) {
				let pv = ParamValue::Bool(item.horizontal);
				if !kframe::inst_set_list_field(&mut self.inst, 6, path, index, "horizontal", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.show_mdb != item.show_mdb) {
				let pv = ParamValue::Bool(item.show_mdb);
				if !kframe::inst_set_list_field(&mut self.inst, 6, path, index, "show_mdb", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.show_store != item.show_store) {
				let pv = ParamValue::Bool(item.show_store);
				if !kframe::inst_set_list_field(&mut self.inst, 6, path, index, "show_store", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.show_edit != item.show_edit) {
				let pv = ParamValue::Bool(item.show_edit);
				if !kframe::inst_set_list_field(&mut self.inst, 6, path, index, "show_edit", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.show_find != item.show_find) {
				let pv = ParamValue::Bool(item.show_find);
				if !kframe::inst_set_list_field(&mut self.inst, 6, path, index, "show_find", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.find_status != item.find_status) {
				let pv = ParamValue::Text(item.find_status.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 6, path, index, "find_status", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.curline != item.curline) {
				let pv = ParamValue::Num(item.curline);
				if !kframe::inst_set_list_field(&mut self.inst, 6, path, index, "curline", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.curline_on != item.curline_on) {
				let pv = ParamValue::Bool(item.curline_on);
				if !kframe::inst_set_list_field(&mut self.inst, 6, path, index, "curline_on", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.gutter != item.gutter) {
				let pv = ParamValue::Text(item.gutter.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 6, path, index, "gutter", &pv) {
					return false;
				}
			}
			let child_path = if path.is_empty() {
				format!("{index}.crumbs")
			} else {
				format!("{path}.{index}.crumbs")
			};
			let previous_crumbs = previous.map(|previous| previous.crumbs.as_slice());
			if !self.set_rootcrumbs_path(&child_path, &item.crumbs, previous_crumbs) {
				return false;
			}
			let child_path = if path.is_empty() {
				format!("{index}.tabs")
			} else {
				format!("{path}.{index}.tabs")
			};
			let previous_tabs = previous.map(|previous| previous.tabs.as_slice());
			if !self.set_roottabs_path(&child_path, &item.tabs, previous_tabs) {
				return false;
			}
			let child_path = if path.is_empty() {
				format!("{index}.children")
			} else {
				format!("{path}.{index}.children")
			};
			let previous_children = previous.map(|previous| previous.children.as_slice());
			if !self.set_root_path(&child_path, &item.children, previous_children) {
				return false;
			}
		}
		true
	}

	fn validate_rootcrumbs(items: &[RootCrumbsItem]) -> bool {
		let Ok(_) = i32::try_from(items.len()) else {
			return false;
		};
		let mut keys = std::collections::HashSet::with_capacity(items.len());
		for (index, item) in items.iter().enumerate() {
			let key = item.key.clone().unwrap_or_else(|| index.to_string());
			if key.is_empty() || !keys.insert(key) {
				return false;
			}
		}
		true
	}

	fn set_rootcrumbs_path(
		&mut self,
		path: &str,
		items: &[RootCrumbsItem],
		previous: Option<&[RootCrumbsItem]>,
	) -> bool {
		let Ok(len) = i32::try_from(items.len()) else {
			return false;
		};
		if !kframe::inst_set_list_len(&mut self.inst, 6, path, len) {
			return false;
		}
		for (item_index, item) in items.iter().enumerate() {
			let previous = previous.and_then(|items| items.get(item_index));
			if previous == Some(item) {
				continue;
			}
			let Ok(index) = i32::try_from(item_index) else {
				return false;
			};
			if previous.is_none_or(|previous| previous.key != item.key) {
				let key = item.key.clone().unwrap_or_else(|| item_index.to_string());
				if !kframe::inst_set_list_key(&mut self.inst, 6, path, index, &key) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.seg != item.seg) {
				let pv = ParamValue::Text(item.seg.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 6, path, index, "seg", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.letter != item.letter) {
				let pv = ParamValue::Text(item.letter.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 6, path, index, "letter", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.last != item.last) {
				let pv = ParamValue::Bool(item.last);
				if !kframe::inst_set_list_field(&mut self.inst, 6, path, index, "last", &pv) {
					return false;
				}
			}
		}
		true
	}

	fn validate_roottabs(items: &[RootTabsItem]) -> bool {
		let Ok(_) = i32::try_from(items.len()) else {
			return false;
		};
		let mut keys = std::collections::HashSet::with_capacity(items.len());
		for (index, item) in items.iter().enumerate() {
			let key = item.key.clone().unwrap_or_else(|| index.to_string());
			if key.is_empty() || !keys.insert(key) {
				return false;
			}
		}
		true
	}

	fn set_roottabs_path(
		&mut self,
		path: &str,
		items: &[RootTabsItem],
		previous: Option<&[RootTabsItem]>,
	) -> bool {
		let Ok(len) = i32::try_from(items.len()) else {
			return false;
		};
		if !kframe::inst_set_list_len(&mut self.inst, 6, path, len) {
			return false;
		}
		for (item_index, item) in items.iter().enumerate() {
			let previous = previous.and_then(|items| items.get(item_index));
			if previous == Some(item) {
				continue;
			}
			let Ok(index) = i32::try_from(item_index) else {
				return false;
			};
			if previous.is_none_or(|previous| previous.key != item.key) {
				let key = item.key.clone().unwrap_or_else(|| item_index.to_string());
				if !kframe::inst_set_list_key(&mut self.inst, 6, path, index, &key) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.name != item.name) {
				let pv = ParamValue::Text(item.name.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 6, path, index, "name", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.note != item.note) {
				let pv = ParamValue::Text(item.note.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 6, path, index, "note", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.tint != item.tint) {
				let pv = ParamValue::Color(item.tint);
				if !kframe::inst_set_list_field(&mut self.inst, 6, path, index, "tint", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.badge != item.badge) {
				let pv = ParamValue::Text(item.badge.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 6, path, index, "badge", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.active != item.active) {
				let pv = ParamValue::Bool(item.active);
				if !kframe::inst_set_list_field(&mut self.inst, 6, path, index, "active", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.hot != item.hot) {
				let pv = ParamValue::Bool(item.hot);
				if !kframe::inst_set_list_field(&mut self.inst, 6, path, index, "hot", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.preview != item.preview) {
				let pv = ParamValue::Bool(item.preview);
				if !kframe::inst_set_list_field(&mut self.inst, 6, path, index, "preview", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.dirty != item.dirty) {
				let pv = ParamValue::Bool(item.dirty);
				if !kframe::inst_set_list_field(&mut self.inst, 6, path, index, "dirty", &pv) {
					return false;
				}
			}
		}
		true
	}

	/// Reconciles list param `root` and all nested lists with the last typed
	/// value.
	pub fn set_root(&mut self, items: &[RootItem]) -> bool {
		if self.root_cache.as_deref() == Some(items) {
			return true;
		}
		if !Self::validate_root(items) {
			return false;
		}
		let previous = self.root_cache.take();
		let updated = self.set_root_path("", items, previous.as_deref());
		self.root_cache = if updated {
			Some(items.to_vec())
		} else {
			previous
		};
		updated
	}

	fn validate_tree(items: &[TreeItem]) -> bool {
		let Ok(_) = i32::try_from(items.len()) else {
			return false;
		};
		let mut keys = std::collections::HashSet::with_capacity(items.len());
		for (index, item) in items.iter().enumerate() {
			let key = item.key.clone().unwrap_or_else(|| index.to_string());
			if key.is_empty() || !keys.insert(key) {
				return false;
			}
		}
		true
	}

	fn set_tree_path(
		&mut self,
		path: &str,
		items: &[TreeItem],
		previous: Option<&[TreeItem]>,
	) -> bool {
		let Ok(len) = i32::try_from(items.len()) else {
			return false;
		};
		if !kframe::inst_set_list_len(&mut self.inst, 19, path, len) {
			return false;
		}
		for (item_index, item) in items.iter().enumerate() {
			let previous = previous.and_then(|items| items.get(item_index));
			if previous == Some(item) {
				continue;
			}
			let Ok(index) = i32::try_from(item_index) else {
				return false;
			};
			if previous.is_none_or(|previous| previous.key != item.key) {
				let key = item.key.clone().unwrap_or_else(|| item_index.to_string());
				if !kframe::inst_set_list_key(&mut self.inst, 19, path, index, &key) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.name != item.name) {
				let pv = ParamValue::Text(item.name.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 19, path, index, "name", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.letter != item.letter) {
				let pv = ParamValue::Text(item.letter.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 19, path, index, "letter", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.icon != item.icon) {
				let pv = ParamValue::Text(item.icon.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 19, path, index, "icon", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.tint != item.tint) {
				let pv = ParamValue::Color(item.tint);
				if !kframe::inst_set_list_field(&mut self.inst, 19, path, index, "tint", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.badge != item.badge) {
				let pv = ParamValue::Text(item.badge.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 19, path, index, "badge", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.indent != item.indent) {
				let pv = ParamValue::Num(item.indent);
				if !kframe::inst_set_list_field(&mut self.inst, 19, path, index, "indent", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.dir != item.dir) {
				let pv = ParamValue::Bool(item.dir);
				if !kframe::inst_set_list_field(&mut self.inst, 19, path, index, "dir", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.open != item.open) {
				let pv = ParamValue::Bool(item.open);
				if !kframe::inst_set_list_field(&mut self.inst, 19, path, index, "open", &pv) {
					return false;
				}
			}
		}
		true
	}

	/// Reconciles list param `tree` and all nested lists with the last typed
	/// value.
	pub fn set_tree(&mut self, items: &[TreeItem]) -> bool {
		if self.tree_cache.as_deref() == Some(items) {
			return true;
		}
		if !Self::validate_tree(items) {
			return false;
		}
		let previous = self.tree_cache.take();
		let updated = self.set_tree_path("", items, previous.as_deref());
		self.tree_cache = if updated {
			Some(items.to_vec())
		} else {
			previous
		};
		updated
	}

	fn validate_scmchanges(items: &[ScmChangesItem]) -> bool {
		let Ok(_) = i32::try_from(items.len()) else {
			return false;
		};
		let mut keys = std::collections::HashSet::with_capacity(items.len());
		for (index, item) in items.iter().enumerate() {
			let key = item.key.clone().unwrap_or_else(|| index.to_string());
			if key.is_empty() || !keys.insert(key) {
				return false;
			}
		}
		true
	}

	fn set_scmchanges_path(
		&mut self,
		path: &str,
		items: &[ScmChangesItem],
		previous: Option<&[ScmChangesItem]>,
	) -> bool {
		let Ok(len) = i32::try_from(items.len()) else {
			return false;
		};
		if !kframe::inst_set_list_len(&mut self.inst, 20, path, len) {
			return false;
		}
		for (item_index, item) in items.iter().enumerate() {
			let previous = previous.and_then(|items| items.get(item_index));
			if previous == Some(item) {
				continue;
			}
			let Ok(index) = i32::try_from(item_index) else {
				return false;
			};
			if previous.is_none_or(|previous| previous.key != item.key) {
				let key = item.key.clone().unwrap_or_else(|| item_index.to_string());
				if !kframe::inst_set_list_key(&mut self.inst, 20, path, index, &key) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.file != item.file) {
				let pv = ParamValue::Text(item.file.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 20, path, index, "file", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.badge != item.badge) {
				let pv = ParamValue::Text(item.badge.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 20, path, index, "badge", &pv) {
					return false;
				}
			}
		}
		true
	}

	/// Reconciles list param `scm.changes` and all nested lists with the last
	/// typed value.
	pub fn set_scm_changes(&mut self, items: &[ScmChangesItem]) -> bool {
		if self.scm_changes_cache.as_deref() == Some(items) {
			return true;
		}
		if !Self::validate_scmchanges(items) {
			return false;
		}
		let previous = self.scm_changes_cache.take();
		let updated = self.set_scmchanges_path("", items, previous.as_deref());
		self.scm_changes_cache = if updated {
			Some(items.to_vec())
		} else {
			previous
		};
		updated
	}

	fn validate_chatsessions(items: &[ChatSessionsItem]) -> bool {
		let Ok(_) = i32::try_from(items.len()) else {
			return false;
		};
		let mut keys = std::collections::HashSet::with_capacity(items.len());
		for (index, item) in items.iter().enumerate() {
			let key = item.key.clone().unwrap_or_else(|| index.to_string());
			if key.is_empty() || !keys.insert(key) {
				return false;
			}
		}
		true
	}

	fn set_chatsessions_path(
		&mut self,
		path: &str,
		items: &[ChatSessionsItem],
		previous: Option<&[ChatSessionsItem]>,
	) -> bool {
		let Ok(len) = i32::try_from(items.len()) else {
			return false;
		};
		if !kframe::inst_set_list_len(&mut self.inst, 21, path, len) {
			return false;
		}
		for (item_index, item) in items.iter().enumerate() {
			let previous = previous.and_then(|items| items.get(item_index));
			if previous == Some(item) {
				continue;
			}
			let Ok(index) = i32::try_from(item_index) else {
				return false;
			};
			if previous.is_none_or(|previous| previous.key != item.key) {
				let key = item.key.clone().unwrap_or_else(|| item_index.to_string());
				if !kframe::inst_set_list_key(&mut self.inst, 21, path, index, &key) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.title != item.title) {
				let pv = ParamValue::Text(item.title.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 21, path, index, "title", &pv) {
					return false;
				}
			}
		}
		true
	}

	/// Reconciles list param `chat.sessions` and all nested lists with the last
	/// typed value.
	pub fn set_chat_sessions(&mut self, items: &[ChatSessionsItem]) -> bool {
		if self.chat_sessions_cache.as_deref() == Some(items) {
			return true;
		}
		if !Self::validate_chatsessions(items) {
			return false;
		}
		let previous = self.chat_sessions_cache.take();
		let updated = self.set_chatsessions_path("", items, previous.as_deref());
		self.chat_sessions_cache = if updated {
			Some(items.to_vec())
		} else {
			previous
		};
		updated
	}

	fn validate_problemsrows(items: &[ProblemsRowsItem]) -> bool {
		let Ok(_) = i32::try_from(items.len()) else {
			return false;
		};
		let mut keys = std::collections::HashSet::with_capacity(items.len());
		for (index, item) in items.iter().enumerate() {
			let key = item.key.clone().unwrap_or_else(|| index.to_string());
			if key.is_empty() || !keys.insert(key) {
				return false;
			}
		}
		true
	}

	fn set_problemsrows_path(
		&mut self,
		path: &str,
		items: &[ProblemsRowsItem],
		previous: Option<&[ProblemsRowsItem]>,
	) -> bool {
		let Ok(len) = i32::try_from(items.len()) else {
			return false;
		};
		if !kframe::inst_set_list_len(&mut self.inst, 24, path, len) {
			return false;
		}
		for (item_index, item) in items.iter().enumerate() {
			let previous = previous.and_then(|items| items.get(item_index));
			if previous == Some(item) {
				continue;
			}
			let Ok(index) = i32::try_from(item_index) else {
				return false;
			};
			if previous.is_none_or(|previous| previous.key != item.key) {
				let key = item.key.clone().unwrap_or_else(|| item_index.to_string());
				if !kframe::inst_set_list_key(&mut self.inst, 24, path, index, &key) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.icon != item.icon) {
				let pv = ParamValue::Text(item.icon.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 24, path, index, "icon", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.file != item.file) {
				let pv = ParamValue::Text(item.file.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 24, path, index, "file", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.line != item.line) {
				let pv = ParamValue::Text(item.line.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 24, path, index, "line", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.msg != item.msg) {
				let pv = ParamValue::Text(item.msg.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 24, path, index, "msg", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.tint != item.tint) {
				let pv = ParamValue::Color(item.tint);
				if !kframe::inst_set_list_field(&mut self.inst, 24, path, index, "tint", &pv) {
					return false;
				}
			}
		}
		true
	}

	/// Reconciles list param `problems.rows` and all nested lists with the last
	/// typed value.
	pub fn set_problems_rows(&mut self, items: &[ProblemsRowsItem]) -> bool {
		if self.problems_rows_cache.as_deref() == Some(items) {
			return true;
		}
		if !Self::validate_problemsrows(items) {
			return false;
		}
		let previous = self.problems_rows_cache.take();
		let updated = self.set_problemsrows_path("", items, previous.as_deref());
		self.problems_rows_cache = if updated {
			Some(items.to_vec())
		} else {
			previous
		};
		updated
	}

	fn validate_searchresults(items: &[SearchResultsItem]) -> bool {
		let Ok(_) = i32::try_from(items.len()) else {
			return false;
		};
		let mut keys = std::collections::HashSet::with_capacity(items.len());
		for (index, item) in items.iter().enumerate() {
			let key = item.key.clone().unwrap_or_else(|| index.to_string());
			if key.is_empty() || !keys.insert(key) {
				return false;
			}
		}
		true
	}

	fn set_searchresults_path(
		&mut self,
		path: &str,
		items: &[SearchResultsItem],
		previous: Option<&[SearchResultsItem]>,
	) -> bool {
		let Ok(len) = i32::try_from(items.len()) else {
			return false;
		};
		if !kframe::inst_set_list_len(&mut self.inst, 30, path, len) {
			return false;
		}
		for (item_index, item) in items.iter().enumerate() {
			let previous = previous.and_then(|items| items.get(item_index));
			if previous == Some(item) {
				continue;
			}
			let Ok(index) = i32::try_from(item_index) else {
				return false;
			};
			if previous.is_none_or(|previous| previous.key != item.key) {
				let key = item.key.clone().unwrap_or_else(|| item_index.to_string());
				if !kframe::inst_set_list_key(&mut self.inst, 30, path, index, &key) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.file != item.file) {
				let pv = ParamValue::Text(item.file.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 30, path, index, "file", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.line != item.line) {
				let pv = ParamValue::Text(item.line.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 30, path, index, "line", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.preview != item.preview) {
				let pv = ParamValue::Text(item.preview.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 30, path, index, "preview", &pv) {
					return false;
				}
			}
		}
		true
	}

	/// Reconciles list param `search.results` and all nested lists with the last
	/// typed value.
	pub fn set_search_results(&mut self, items: &[SearchResultsItem]) -> bool {
		if self.search_results_cache.as_deref() == Some(items) {
			return true;
		}
		if !Self::validate_searchresults(items) {
			return false;
		}
		let previous = self.search_results_cache.take();
		let updated = self.set_searchresults_path("", items, previous.as_deref());
		self.search_results_cache = if updated {
			Some(items.to_vec())
		} else {
			previous
		};
		updated
	}

	fn validate_extrows(items: &[ExtRowsItem]) -> bool {
		let Ok(_) = i32::try_from(items.len()) else {
			return false;
		};
		let mut keys = std::collections::HashSet::with_capacity(items.len());
		for (index, item) in items.iter().enumerate() {
			let key = item.key.clone().unwrap_or_else(|| index.to_string());
			if key.is_empty() || !keys.insert(key) {
				return false;
			}
		}
		true
	}

	fn set_extrows_path(
		&mut self,
		path: &str,
		items: &[ExtRowsItem],
		previous: Option<&[ExtRowsItem]>,
	) -> bool {
		let Ok(len) = i32::try_from(items.len()) else {
			return false;
		};
		if !kframe::inst_set_list_len(&mut self.inst, 31, path, len) {
			return false;
		}
		for (item_index, item) in items.iter().enumerate() {
			let previous = previous.and_then(|items| items.get(item_index));
			if previous == Some(item) {
				continue;
			}
			let Ok(index) = i32::try_from(item_index) else {
				return false;
			};
			if previous.is_none_or(|previous| previous.key != item.key) {
				let key = item.key.clone().unwrap_or_else(|| item_index.to_string());
				if !kframe::inst_set_list_key(&mut self.inst, 31, path, index, &key) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.name != item.name) {
				let pv = ParamValue::Text(item.name.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 31, path, index, "name", &pv) {
					return false;
				}
			}
			if previous.is_none_or(|previous| previous.publisher != item.publisher) {
				let pv = ParamValue::Text(item.publisher.clone());
				if !kframe::inst_set_list_field(&mut self.inst, 31, path, index, "publisher", &pv) {
					return false;
				}
			}
		}
		true
	}

	/// Reconciles list param `ext.rows` and all nested lists with the last typed
	/// value.
	pub fn set_ext_rows(&mut self, items: &[ExtRowsItem]) -> bool {
		if self.ext_rows_cache.as_deref() == Some(items) {
			return true;
		}
		if !Self::validate_extrows(items) {
			return false;
		}
		let previous = self.ext_rows_cache.take();
		let updated = self.set_extrows_path("", items, previous.as_deref());
		self.ext_rows_cache = if updated {
			Some(items.to_vec())
		} else {
			previous
		};
		updated
	}

	/// Set param `menu.open` (bool); false = rejected by the kernel.
	pub fn set_menu_open(&mut self, v: bool) -> bool {
		let pv = ParamValue::Bool(v);
		kframe::inst_set_param(&mut self.inst, 0, &pv)
	}

	/// Set param `menu.anchor` (text); false = rejected by the kernel.
	pub fn set_menu_anchor(&mut self, v: &str) -> bool {
		let pv = ParamValue::Text(v.to_string());
		kframe::inst_set_param(&mut self.inst, 1, &pv)
	}

	/// Set param `qo.open` (bool); false = rejected by the kernel.
	pub fn set_qo_open(&mut self, v: bool) -> bool {
		let pv = ParamValue::Bool(v);
		kframe::inst_set_param(&mut self.inst, 3, &pv)
	}

	/// Set param `qo.sel` (num); false = rejected by the kernel.
	pub fn set_qo_sel(&mut self, v: f64) -> bool {
		let pv = ParamValue::Num(v);
		kframe::inst_set_param(&mut self.inst, 4, &pv)
	}

	/// Set param `nav.canback` (bool); false = rejected by the kernel.
	pub fn set_nav_canback(&mut self, v: bool) -> bool {
		let pv = ParamValue::Bool(v);
		kframe::inst_set_param(&mut self.inst, 7, &pv)
	}

	/// Set param `nav.canfwd` (bool); false = rejected by the kernel.
	pub fn set_nav_canfwd(&mut self, v: bool) -> bool {
		let pv = ParamValue::Bool(v);
		kframe::inst_set_param(&mut self.inst, 8, &pv)
	}

	/// Set param `status.lang` (text); false = rejected by the kernel.
	pub fn set_status_lang(&mut self, v: &str) -> bool {
		let pv = ParamValue::Text(v.to_string());
		kframe::inst_set_param(&mut self.inst, 9, &pv)
	}

	/// Set param `status.caret` (text); false = rejected by the kernel.
	pub fn set_status_caret(&mut self, v: &str) -> bool {
		let pv = ParamValue::Text(v.to_string());
		kframe::inst_set_param(&mut self.inst, 10, &pv)
	}

	/// Set param `status.errs` (text); false = rejected by the kernel.
	pub fn set_status_errs(&mut self, v: &str) -> bool {
		let pv = ParamValue::Text(v.to_string());
		kframe::inst_set_param(&mut self.inst, 11, &pv)
	}

	/// Set param `status.warns` (text); false = rejected by the kernel.
	pub fn set_status_warns(&mut self, v: &str) -> bool {
		let pv = ParamValue::Text(v.to_string());
		kframe::inst_set_param(&mut self.inst, 12, &pv)
	}

	/// Set param `panel.problems` (bool); false = rejected by the kernel.
	pub fn set_panel_problems(&mut self, v: bool) -> bool {
		let pv = ParamValue::Bool(v);
		kframe::inst_set_param(&mut self.inst, 13, &pv)
	}

	/// Set param `panel.output` (bool); false = rejected by the kernel.
	pub fn set_panel_output(&mut self, v: bool) -> bool {
		let pv = ParamValue::Bool(v);
		kframe::inst_set_param(&mut self.inst, 14, &pv)
	}

	/// Set param `panel.debugc` (bool); false = rejected by the kernel.
	pub fn set_panel_debugc(&mut self, v: bool) -> bool {
		let pv = ParamValue::Bool(v);
		kframe::inst_set_param(&mut self.inst, 15, &pv)
	}

	/// Set param `panel.terminal` (bool); false = rejected by the kernel.
	pub fn set_panel_terminal(&mut self, v: bool) -> bool {
		let pv = ParamValue::Bool(v);
		kframe::inst_set_param(&mut self.inst, 16, &pv)
	}

	/// Set param `panel.ports` (bool); false = rejected by the kernel.
	pub fn set_panel_ports(&mut self, v: bool) -> bool {
		let pv = ParamValue::Bool(v);
		kframe::inst_set_param(&mut self.inst, 17, &pv)
	}

	/// Set param `panel.termlog` (text); false = rejected by the kernel.
	pub fn set_panel_termlog(&mut self, v: &str) -> bool {
		let pv = ParamValue::Text(v.to_string());
		kframe::inst_set_param(&mut self.inst, 18, &pv)
	}

	/// Set param `chat.typing` (bool); false = rejected by the kernel.
	pub fn set_chat_typing(&mut self, v: bool) -> bool {
		let pv = ParamValue::Bool(v);
		kframe::inst_set_param(&mut self.inst, 22, &pv)
	}

	/// Set param `problems.filtering` (bool); false = rejected by the kernel.
	pub fn set_problems_filtering(&mut self, v: bool) -> bool {
		let pv = ParamValue::Bool(v);
		kframe::inst_set_param(&mut self.inst, 23, &pv)
	}

	/// Set param `sidebar.explorer` (bool); false = rejected by the kernel.
	pub fn set_sidebar_explorer(&mut self, v: bool) -> bool {
		let pv = ParamValue::Bool(v);
		kframe::inst_set_param(&mut self.inst, 25, &pv)
	}

	/// Set param `sidebar.search` (bool); false = rejected by the kernel.
	pub fn set_sidebar_search(&mut self, v: bool) -> bool {
		let pv = ParamValue::Bool(v);
		kframe::inst_set_param(&mut self.inst, 26, &pv)
	}

	/// Set param `sidebar.scm` (bool); false = rejected by the kernel.
	pub fn set_sidebar_scm(&mut self, v: bool) -> bool {
		let pv = ParamValue::Bool(v);
		kframe::inst_set_param(&mut self.inst, 27, &pv)
	}

	/// Set param `sidebar.debug` (bool); false = rejected by the kernel.
	pub fn set_sidebar_debug(&mut self, v: bool) -> bool {
		let pv = ParamValue::Bool(v);
		kframe::inst_set_param(&mut self.inst, 28, &pv)
	}

	/// Set param `sidebar.ext` (bool); false = rejected by the kernel.
	pub fn set_sidebar_ext(&mut self, v: bool) -> bool {
		let pv = ParamValue::Bool(v);
		kframe::inst_set_param(&mut self.inst, 29, &pv)
	}
}
