// GENERATED by `bun demos/vscode/gen_fs.ts` from demos/vscode/web/fsmodel.js —
// do not edit.

//! Static file-system model for the native VS Code demo, shared verbatim
//! with the web host (`demos/vscode/web/fsmodel.js`).

/// One explorer entry, depth-first with parents before children.
pub struct FsEntry {
	pub path:   &'static str,
	pub name:   &'static str,
	pub letter: &'static str,
	pub icon:   &'static str,
	pub tint:   &'static str,
	pub badge:  &'static str,
	pub dir:    bool,
	pub depth:  u32,
}

/// The explorer tree, flattened depth-first.
pub static ENTRIES: &[FsEntry] = &[
	FsEntry {
		path:   "build",
		name:   "build",
		letter: "",
		icon:   "",
		tint:   "#909094",
		badge:  "",
		dir:    true,
		depth:  0,
	},
	FsEntry {
		path:   "include",
		name:   "include",
		letter: "",
		icon:   "",
		tint:   "#909094",
		badge:  "",
		dir:    true,
		depth:  0,
	},
	FsEntry {
		path:   "include/agentfs",
		name:   "agentfs",
		letter: "",
		icon:   "",
		tint:   "#A63D5B",
		badge:  "",
		dir:    true,
		depth:  1,
	},
	FsEntry {
		path:   "include/agentfs/cid.hpp",
		name:   "cid.hpp",
		letter: "h",
		icon:   "",
		tint:   "#707074",
		badge:  "",
		dir:    false,
		depth:  2,
	},
	FsEntry {
		path:   "include/agentfs/launch.hpp",
		name:   "launch.hpp",
		letter: "h",
		icon:   "",
		tint:   "#707074",
		badge:  "",
		dir:    false,
		depth:  2,
	},
	FsEntry {
		path:   "include/agentfs/mdb.hpp",
		name:   "mdb.hpp",
		letter: "h",
		icon:   "",
		tint:   "#A63D5B",
		badge:  "2",
		dir:    false,
		depth:  2,
	},
	FsEntry {
		path:   "include/agentfs/node.hpp",
		name:   "node.hpp",
		letter: "h",
		icon:   "",
		tint:   "#707074",
		badge:  "",
		dir:    false,
		depth:  2,
	},
	FsEntry {
		path:   "include/agentfs/overlay.hpp",
		name:   "overlay.hpp",
		letter: "h",
		icon:   "",
		tint:   "#707074",
		badge:  "",
		dir:    false,
		depth:  2,
	},
	FsEntry {
		path:   "include/agentfs/path.hpp",
		name:   "path.hpp",
		letter: "h",
		icon:   "",
		tint:   "#707074",
		badge:  "",
		dir:    false,
		depth:  2,
	},
	FsEntry {
		path:   "include/agentfs/store.hpp",
		name:   "store.hpp",
		letter: "h",
		icon:   "",
		tint:   "#A63D5B",
		badge:  "2",
		dir:    false,
		depth:  2,
	},
	FsEntry {
		path:   "scripts",
		name:   "scripts",
		letter: "",
		icon:   "",
		tint:   "#909094",
		badge:  "",
		dir:    true,
		depth:  0,
	},
	FsEntry {
		path:   "src",
		name:   "src",
		letter: "",
		icon:   "",
		tint:   "#909094",
		badge:  "",
		dir:    true,
		depth:  0,
	},
	FsEntry {
		path:   "src/cli",
		name:   "cli",
		letter: "",
		icon:   "",
		tint:   "#909094",
		badge:  "",
		dir:    true,
		depth:  1,
	},
	FsEntry {
		path:   "src/cli/main.cpp",
		name:   "main.cpp",
		letter: "C",
		icon:   "",
		tint:   "#707074",
		badge:  "",
		dir:    false,
		depth:  2,
	},
	FsEntry {
		path:   "src/core",
		name:   "core",
		letter: "",
		icon:   "",
		tint:   "#909094",
		badge:  "",
		dir:    true,
		depth:  1,
	},
	FsEntry {
		path:   "src/core/launch.cpp",
		name:   "launch.cpp",
		letter: "C",
		icon:   "",
		tint:   "#707074",
		badge:  "",
		dir:    false,
		depth:  2,
	},
	FsEntry {
		path:   "src/core/mdb.cpp",
		name:   "mdb.cpp",
		letter: "C",
		icon:   "",
		tint:   "#707074",
		badge:  "",
		dir:    false,
		depth:  2,
	},
	FsEntry {
		path:   "src/core/overlay.cpp",
		name:   "overlay.cpp",
		letter: "C",
		icon:   "",
		tint:   "#707074",
		badge:  "",
		dir:    false,
		depth:  2,
	},
	FsEntry {
		path:   "src/core/path.cpp",
		name:   "path.cpp",
		letter: "C",
		icon:   "",
		tint:   "#707074",
		badge:  "",
		dir:    false,
		depth:  2,
	},
	FsEntry {
		path:   "src/core/store.cpp",
		name:   "store.cpp",
		letter: "C",
		icon:   "",
		tint:   "#707074",
		badge:  "",
		dir:    false,
		depth:  2,
	},
	FsEntry {
		path:   "src/hook",
		name:   "hook",
		letter: "",
		icon:   "",
		tint:   "#909094",
		badge:  "",
		dir:    true,
		depth:  1,
	},
	FsEntry {
		path:   "src/hook/context.cpp",
		name:   "context.cpp",
		letter: "C",
		icon:   "",
		tint:   "#707074",
		badge:  "",
		dir:    false,
		depth:  2,
	},
	FsEntry {
		path:   "src/hook/hook.hpp",
		name:   "hook.hpp",
		letter: "h",
		icon:   "",
		tint:   "#707074",
		badge:  "",
		dir:    false,
		depth:  2,
	},
	FsEntry {
		path:   "src/hook/hooks_path.cpp",
		name:   "hooks_path.cpp",
		letter: "C",
		icon:   "",
		tint:   "#707074",
		badge:  "",
		dir:    false,
		depth:  2,
	},
	FsEntry {
		path:   "src/hook/hooks_proc.cpp",
		name:   "hooks_proc.cpp",
		letter: "C",
		icon:   "",
		tint:   "#707074",
		badge:  "",
		dir:    false,
		depth:  2,
	},
	FsEntry {
		path:   "src/hook/interpose.hpp",
		name:   "interpose.hpp",
		letter: "h",
		icon:   "",
		tint:   "#707074",
		badge:  "",
		dir:    false,
		depth:  2,
	},
	FsEntry {
		path:   "src/hook/spawn.cpp",
		name:   "spawn.cpp",
		letter: "C",
		icon:   "",
		tint:   "#707074",
		badge:  "",
		dir:    false,
		depth:  2,
	},
	FsEntry {
		path:   "src/hook/spawn.hpp",
		name:   "spawn.hpp",
		letter: "h",
		icon:   "",
		tint:   "#707074",
		badge:  "",
		dir:    false,
		depth:  2,
	},
	FsEntry {
		path:   "src/interpose",
		name:   "interpose",
		letter: "",
		icon:   "",
		tint:   "#909094",
		badge:  "",
		dir:    true,
		depth:  1,
	},
	FsEntry {
		path:   "tests",
		name:   "tests",
		letter: "",
		icon:   "",
		tint:   "#909094",
		badge:  "",
		dir:    true,
		depth:  0,
	},
	FsEntry {
		path:   "third_party",
		name:   "third_party",
		letter: "",
		icon:   "",
		tint:   "#909094",
		badge:  "",
		dir:    true,
		depth:  0,
	},
	FsEntry {
		path:   ".clang-format",
		name:   ".clang-format",
		letter: "",
		icon:   "gearfile",
		tint:   "#707074",
		badge:  "",
		dir:    false,
		depth:  0,
	},
	FsEntry {
		path:   ".gitignore",
		name:   ".gitignore",
		letter: "",
		icon:   "branch",
		tint:   "#707074",
		badge:  "",
		dir:    false,
		depth:  0,
	},
	FsEntry {
		path:   "CMakeLists.txt",
		name:   "CMakeLists.txt",
		letter: "",
		icon:   "cmakefile",
		tint:   "#707074",
		badge:  "",
		dir:    false,
		depth:  0,
	},
	FsEntry {
		path:   "demo.sh",
		name:   "demo.sh",
		letter: "",
		icon:   "shellfile",
		tint:   "#707074",
		badge:  "",
		dir:    false,
		depth:  0,
	},
	FsEntry {
		path:   "README.md",
		name:   "README.md",
		letter: "",
		icon:   "markdown",
		tint:   "#707074",
		badge:  "",
		dir:    false,
		depth:  0,
	},
];

/// Directories open at first launch.
pub static DEFAULT_OPEN: &[&str] =
	&["include", "include/agentfs", "src", "src/cli", "src/core", "src/hook"];

/// Initial file contents by path.
pub static CONTENTS: &[(&str, &str)] = &[
	(
		"include/agentfs/cid.hpp",
		r"#pragma once
#include <array>
#include <cstddef>
#include <span>
#include <string>

namespace agentfs {
struct cid {
   std::array<std::byte, 32> bytes{};
   friend bool operator==( const cid&, const cid& ) = default;
};
cid hash( std::span<const std::byte> data );
std::string to_string( const cid& value );
} // namespace agentfs",
	),
	(
		"include/agentfs/launch.hpp",
		r"#pragma once
#include <filesystem>
#include <string>
#include <vector>

namespace agentfs {
struct launch_options {
   std::filesystem::path image;
   std::vector<std::string> command;
   bool writable = false;
};
int launch( const launch_options& options );
} // namespace agentfs",
	),
	(
		"include/agentfs/mdb.hpp",
		r"#pragma once
#include <lmdb.h>
#include <cstddef>
#include <cstdint>
#include <span>
#include <string_view>
#include <utility>

namespace agentfs::mdb
{
   struct error
   {
      int code = 0;
      std::string_view message() const;
   };

   struct value
   {
      MDB_val raw{};
      std::span<const std::byte> bytes() const;
   };

   struct database
   {
      MDB_dbi handle = 0;
      constexpr explicit operator bool() const { return handle != 0; }
   };

   // Owns an LMDB environment handle.
   //
   struct environment
   {
      MDB_env* handle = nullptr;

   // The handle remains null until open succeeds.
   //
   static environment open( std::string_view path );

   constexpr environment() = default;
   constexpr environment( environment&& other ) noexcept : handle( std::exchange( other
   constexpr environment& operator=( environment&& other ) noexcept
   {
      std::swap( handle, other.handle );
      return *this;
   }
   environment( const environment& )            = delete;
   environment& operator=( const environment& ) = delete;
   ~environment() { reset(); }

   void reset()
   {
      if ( MDB_env* previous = std::exchange( handle, nullptr ) )
         mdb_env_close( previous );
   }
   constexpr explicit operator bool() const { return handle != nullptr; }
};

// Owns a transaction handle and aborts it unless it is committed first.
//
struct transaction
{
   MDB_txn* handle = nullptr;

   constexpr transaction() = default;
   constexpr explicit transaction( MDB_txn* handle ) : handle( handle ) {}
   constexpr transaction( transaction&& other ) noexcept : handle( std::exchange( other
   constexpr transaction& operator=( transaction&& other ) noexcept
   {
      std::swap( handle, other.handle );
      return *this;
   }
   transaction( const transaction& )            = delete;
   transaction& operator=( const transaction& ) = delete;
   ~transaction() { abort(); }

   void abort()
   {
      if ( MDB_txn* previous = std::exchange( handle, nullptr ) )
         mdb_txn_abort( previous );",
	),
	(
		"include/agentfs/node.hpp",
		r"#pragma once
#include <cstdint>
#include <string>
#include <vector>

namespace agentfs {
enum class node_kind { file, directory, symlink };
struct node_record {
   node_kind kind = node_kind::file;
   uint64_t size = 0;
   uint64_t modified_ns = 0;
   std::vector<std::byte> payload;
};
} // namespace agentfs",
	),
	(
		"include/agentfs/overlay.hpp",
		r#"#pragma once
#include <filesystem>
#include <string_view>
#include "store.hpp"

namespace agentfs {
class overlay {
 public:
   explicit overlay( store& image );
   bool contains( std::string_view path ) const;
   void materialize( const std::filesystem::path& target ) const;
 private:
   store* image_;
};
} // namespace agentfs"#,
	),
	(
		"include/agentfs/path.hpp",
		r"#pragma once
#include <string>
#include <string_view>
#include <vector>

namespace agentfs::path {
std::string normalize( std::string_view input );
std::string parent( std::string_view input );
std::string filename( std::string_view input );
std::vector<std::string_view> components( std::string_view input );
bool is_absolute( std::string_view input );
} // namespace agentfs::path",
	),
	(
		"include/agentfs/store.hpp",
		r#"#pragma once
#include <memory>
#include <span>
#include <string>
#include <string_view>
#include <vector>
#include <xstd/result.hpp>
#include "cid.hpp"
#include "mdb.hpp"
#include "node.hpp"

namespace agentfs
{
   // Wall clock nanoseconds, the unit stored in every node record.
   //
   uint64_t now_ns();

   // One entry of a directory listing.
   //
   struct dir_entry
   {
      std::string name;
      node_kind kind = node_kind::file;
   };

   struct reader;
   struct writer;

   // LMDB backed content addressed filesystem image.
   //
   // Three sub-databases make up the image:
   //   `meta`  - format marker and chunk geometry.
   //   `nodes` - normalized path -> `node_record` plus payload.
   //   `blobs` - `cid` -> chunk bytes, written once per distinct chunk.
   //
   // Reads borrow directly from the memory map, so a `reader` must outlive
   // every span it hands out.
   //
   struct store
   {
      mdb::environment env;
      MDB_dbi meta   = 0;"#,
	),
	(
		"src/cli/main.cpp",
		r#"#include <agentfs/launch.hpp>
#include <iostream>
#include <string>

int main( int argc, char** argv )
{
   if ( argc < 3 ) {
      std::cerr << "usage: agentfs IMAGE COMMAND...\n";
      return 2;
   }
   agentfs::launch_options options;
   options.image = argv[1];
   options.command.assign( argv + 2, argv + argc );
   return agentfs::launch( options );
}"#,
	),
	(
		"src/core/launch.cpp",
		r"#include <agentfs/launch.hpp>
#include <agentfs/overlay.hpp>
#include <agentfs/store.hpp>
#include <stdexcept>

namespace agentfs {
int launch( const launch_options& options )
{
   store image{ options.image };
   overlay mounted{ image };
   return options.command.empty() ? 1 : 0;
}
} // namespace agentfs",
	),
	(
		"src/core/mdb.cpp",
		r"#include <agentfs/mdb.hpp>
#include <system_error>

namespace agentfs::mdb {
std::string_view error::message() const
{
   return mdb_strerror( code );
}
std::span<const std::byte> value::bytes() const
{
   return { static_cast<const std::byte*>( raw.mv_data ), raw.mv_size };
}
} // namespace agentfs::mdb",
	),
	(
		"src/core/overlay.cpp",
		r"#include <agentfs/overlay.hpp>
#include <agentfs/path.hpp>

namespace agentfs {
overlay::overlay( store& image ) : image_( &image ) {}
bool overlay::contains( std::string_view path ) const
{
   auto reader = image_->read();
   return reader.contains( path::normalize( path ) );
}
void overlay::materialize( const std::filesystem::path& target ) const
{
   image_->checkout( target );
}
} // namespace agentfs",
	),
	(
		"src/core/path.cpp",
		r"#include <agentfs/path.hpp>
#include <filesystem>

namespace agentfs::path {
std::string normalize( std::string_view input )
{
   return std::filesystem::path{ input }.lexically_normal().generic_string();
}
std::string filename( std::string_view input )
{
   return std::filesystem::path{ input }.filename().string();
}
bool is_absolute( std::string_view input )
{
   return std::filesystem::path{ input }.is_absolute();
}
} // namespace agentfs::path",
	),
	(
		"src/core/store.cpp",
		r"#include <agentfs/store.hpp>
#include <chrono>

namespace agentfs {
uint64_t now_ns()
{
   const auto now = std::chrono::system_clock::now().time_since_epoch();
   return std::chrono::duration_cast<std::chrono::nanoseconds>( now ).count();
}
store::store( const std::filesystem::path& image )
{
   open_environment( env, image );
}
} // namespace agentfs",
	),
	(
		"src/hook/context.cpp",
		r#"#include "hook.hpp"
#include <cstdlib>
#include <mutex>

namespace agentfs::hook {
context& current_context()
{
   static context value;
   return value;
}
void initialize()
{
   auto& ctx = current_context();
   ctx.root = std::getenv( "AGENTFS_ROOT" );
}
} // namespace agentfs::hook"#,
	),
	(
		"src/hook/hook.hpp",
		r"#pragma once
#include <filesystem>
#include <optional>
#include <string>

namespace agentfs::hook {
struct context {
   std::filesystem::path root;
   bool active = false;
};
context& current_context();
void initialize();
std::optional<std::filesystem::path> redirect( const char* path );
} // namespace agentfs::hook",
	),
	(
		"src/hook/hooks_path.cpp",
		r#"#include "hook.hpp"
#include "interpose.hpp"
#include <fcntl.h>

extern "C" int open( const char* path, int flags, ... )
{
   auto target = agentfs::hook::redirect( path );
   const char* resolved = target ? target->c_str() : path;
   return agentfs::hook::real_open()( resolved, flags );
}

extern "C" int access( const char* path, int mode )
{
   auto target = agentfs::hook::redirect( path );
   return agentfs::hook::real_access()( target ? target->c_str() : path, mode );
}"#,
	),
	(
		"src/hook/hooks_proc.cpp",
		r#"#include "hook.hpp"
#include "spawn.hpp"
#include <unistd.h>

extern "C" int execve( const char* file, char* const argv[], char* const envp[] )
{
   return agentfs::hook::spawn( file, argv, envp );
}

extern "C" pid_t fork()
{
   return agentfs::hook::real_fork()();
}"#,
	),
	(
		"src/hook/interpose.hpp",
		r"#pragma once
#include <dlfcn.h>
#include <mutex>

namespace agentfs::hook {
template<class Function>
Function resolve( const char* name )
{
   return reinterpret_cast<Function>( dlsym( RTLD_NEXT, name ) );
}
using open_fn = int (*)( const char*, int, ... );
using access_fn = int (*)( const char*, int );
using fork_fn = pid_t (*)();
open_fn real_open();
access_fn real_access();
fork_fn real_fork();
} // namespace agentfs::hook",
	),
	(
		"src/hook/spawn.cpp",
		r#"#include "spawn.hpp"
#include "interpose.hpp"
#include <vector>

namespace agentfs::hook {
int spawn( const char* file, char* const argv[], char* const envp[] )
{
   auto environment = augment_environment( envp );
   using execve_fn = int (*)( const char*, char* const[], char* const[] );
   auto next = resolve<execve_fn>( "execve" );
   return next( file, argv, environment.data() );
}
} // namespace agentfs::hook"#,
	),
	(
		"src/hook/spawn.hpp",
		r"#pragma once
#include <string>
#include <vector>

namespace agentfs::hook {
using environment = std::vector<char*>;
environment augment_environment( char* const envp[] );
int spawn(
   const char* file,
   char* const argv[],
   char* const envp[] );
} // namespace agentfs::hook",
	),
	(
		".clang-format",
		r"BasedOnStyle: LLVM
IndentWidth: 3
TabWidth: 3
UseTab: Never
ColumnLimit: 100
BreakBeforeBraces: Allman
AllowShortFunctionsOnASingleLine: Empty
PointerAlignment: Left
ReferenceAlignment: Left
SortIncludes: CaseSensitive
SpaceBeforeParens: ControlStatements",
	),
	(
		".gitignore",
		r"build/
.cache/
compile_commands.json
.DS_Store
*.swp
*.swo
*.dylib
*.so
*.o
agentfs.img
coverage/",
	),
	(
		"CMakeLists.txt",
		r"cmake_minimum_required(VERSION 3.24)
project(agentfs-cxx LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_library(agentfs
  src/core/launch.cpp
  src/core/mdb.cpp
  src/core/overlay.cpp
  src/core/path.cpp
  src/core/store.cpp)
target_include_directories(agentfs PUBLIC include)
target_link_libraries(agentfs PUBLIC lmdb)

add_executable(agentfs-cli src/cli/main.cpp)
target_link_libraries(agentfs-cli PRIVATE agentfs)",
	),
	(
		"demo.sh",
		r#"#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "$0")" && pwd)"
image="${TMPDIR:-/tmp}/agentfs-demo.mdb"
rm -rf "$image"
cmake -S "$root" -B "$root/build"
cmake --build "$root/build"
exec "$root/build/agentfs-cli" "$image" /bin/sh"#,
	),
	(
		"README.md",
		r"# agentfs-cxx

A content-addressed filesystem image for isolated build agents.

## Build

```sh
cmake -S . -B build
cmake --build build
```

Run `./demo.sh` to create an image and launch a shell backed by it.",
	),
];
