[package]
name = "slab-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
default-run = "slab"
[[bin]]
name = "slab"
path = "src/main.rs"

[[bench]]
name = "frame"
harness = false

[dependencies]
slab-syntax = { path = "../slab-syntax" }
slab-slir = { path = "../slab-slir" }
slab-compile = { path = "../slab-compile" }
slab-fonts = { path = "../slab-fonts" }
slab-kernel = { path = "../slab-kernel" }
slab-drive = { path = "../slab-drive" }
slab-lsp = { path = "../slab-lsp" }
serde_json.workspace = true
