// GENERATED by `cargo run -p xtask -- gen-caps` from spec/support.toml — do not edit
//! Platform × feature capability tables (spec/SPEC.md §Platform support).
//! Drivers look degradations up here instead of hardcoding them.

/// Feature levels.
pub const NONE: u8 = 0;
pub const DEGRADED: u8 = 1;
pub const FULL: u8 = 2;

/// Client columns; the index is the kernel client code (`inst_set_env`).
pub const CLIENTS: [&str; 5] = ["web", "gpu", "tui", "svg", "png"];

/// Feature rows, chart order.
pub const FEATURES: [&str; 40] = [
    "radius",
    "shadow",
    "blur",
    "backdrop",
    "gradient",
    "gradient-conic",
    "gradient-text",
    "path",
    "path-runtime",
    "icon",
    "image",
    "img-runtime",
    "rotation",
    "scale",
    "tilt",
    "smooth",
    "grain",
    "mask",
    "backdrop-fade",
    "animation",
    "text-keyframes",
    "transition",
    "themes",
    "input",
    "ime",
    "scroll",
    "scroll-cross",
    "scroll-reveal",
    "sticky",
    "divider",
    "holes",
    "lists",
    "lists-nested",
    "para-runs",
    "lists-virtual",
    "popover",
    "signals",
    "a11y",
    "text-edit",
    "text-raster",
];

/// `LEVELS[feature][client]`.
pub const LEVELS: [[u8; 5]; 40] = [
    [FULL, FULL, DEGRADED, FULL, FULL],             // radius
    [FULL, DEGRADED, NONE, DEGRADED, FULL],         // shadow
    [FULL, FULL, NONE, FULL, FULL],                 // blur
    [FULL, FULL, NONE, DEGRADED, FULL],             // backdrop
    [DEGRADED, DEGRADED, DEGRADED, FULL, FULL],     // gradient
    [FULL, DEGRADED, DEGRADED, DEGRADED, FULL],     // gradient-conic
    [FULL, DEGRADED, DEGRADED, FULL, FULL],         // gradient-text
    [FULL, FULL, DEGRADED, FULL, FULL],             // path
    [FULL, FULL, DEGRADED, FULL, FULL],             // path-runtime
    [FULL, FULL, DEGRADED, FULL, FULL],             // icon
    [FULL, FULL, DEGRADED, FULL, FULL],             // image
    [FULL, FULL, DEGRADED, FULL, FULL],             // img-runtime
    [FULL, FULL, NONE, FULL, FULL],                 // rotation
    [FULL, FULL, NONE, FULL, FULL],                 // scale
    [FULL, FULL, NONE, DEGRADED, FULL],             // tilt
    [DEGRADED, DEGRADED, DEGRADED, FULL, FULL],     // smooth
    [FULL, FULL, NONE, DEGRADED, FULL],             // grain
    [FULL, FULL, DEGRADED, FULL, FULL],             // mask
    [DEGRADED, DEGRADED, NONE, DEGRADED, DEGRADED], // backdrop-fade
    [FULL, FULL, FULL, DEGRADED, DEGRADED],         // animation
    [FULL, FULL, FULL, DEGRADED, FULL],             // text-keyframes
    [FULL, FULL, FULL, NONE, NONE],                 // transition
    [FULL, FULL, FULL, FULL, FULL],                 // themes
    [FULL, FULL, DEGRADED, NONE, NONE],             // input
    [FULL, DEGRADED, NONE, NONE, NONE],             // ime
    [FULL, FULL, FULL, NONE, NONE],                 // scroll
    [FULL, FULL, FULL, NONE, NONE],                 // scroll-cross
    [FULL, FULL, FULL, NONE, NONE],                 // scroll-reveal
    [FULL, FULL, FULL, NONE, NONE],                 // sticky
    [FULL, FULL, FULL, DEGRADED, DEGRADED],         // divider
    [FULL, FULL, NONE, DEGRADED, DEGRADED],         // holes
    [FULL, FULL, FULL, FULL, FULL],                 // lists
    [FULL, FULL, FULL, FULL, FULL],                 // lists-nested
    [FULL, FULL, FULL, FULL, FULL],                 // para-runs
    [FULL, FULL, FULL, FULL, FULL],                 // lists-virtual
    [FULL, FULL, FULL, FULL, FULL],                 // popover
    [FULL, FULL, FULL, NONE, NONE],                 // signals
    [FULL, FULL, NONE, NONE, NONE],                 // a11y
    [FULL, DEGRADED, FULL, NONE, NONE],             // text-edit
    [DEGRADED, FULL, DEGRADED, DEGRADED, FULL],     // text-raster
];

/// `NOTES[feature][client]`: `""` for full, the degradation sentence
/// for degraded, the `cap-*` diag code for none.
pub const NOTES: [[&str; 5]; 40] = [
    // radius
    [
        "",
        "",
        "corner radius collapses to single arc glyphs (radius >= 4u draws ╭ ╮ ╰ ╯, smaller radii draw square corners)",
        "",
        "",
    ],
    // shadow
    [
        "",
        "outset shadows use blurred-SDF approximations",
        "cap-shadow",
        "the shadow spread field is ignored by the SVG filters (research parity; the raster honors it)",
        "",
    ],
    // blur
    ["", "", "cap-blur", "", ""],
    // backdrop
    [
        "",
        "",
        "cap-backdrop",
        "approximated by re-emitting the ops beneath the panel, clipped and blurred, behind it",
        "",
    ],
    // gradient
    [
        "dashed or per-side gradient strokes fall back to their first stop",
        "gradients sample at most 8 stops (cap-gradient-stops)",
        "sampled per cell (linear angle, radial farthest-corner, conic sweep), alpha-composited",
        "",
        "",
    ],
    // gradient-conic
    [
        "",
        "gradients sample at most 8 stops (cap-gradient-stops)",
        "sampled per cell over the paint box",
        "approximated by a 90-wedge fan, each wedge solid at its center sample",
        "",
    ],
    // gradient-text
    [
        "",
        "gradients sample at most 8 stops (cap-gradient-stops)",
        "sampled per cell over the text node's content box",
        "",
        "",
    ],
    // path
    [
        "",
        "",
        "strokes as slope-charred cell runs, fills as even-odd scanline at cell centers",
        "",
        "",
    ],
    // path-runtime
    [
        "",
        "",
        "uses the same cell-center path approximation as compiled path data",
        "",
        "",
    ],
    // icon
    [
        "",
        "",
        "scale transforms are ignored and icon paths render in design-box coordinates",
        "",
        "",
    ],
    // image
    [
        "",
        "",
        "drawn as a shaded placeholder block labeled with the source basename",
        "",
        "",
    ],
    // img-runtime
    [
        "",
        "",
        "drawn as the same shaded placeholder block used for compiled images",
        "",
        "",
    ],
    // rotation
    ["", "", "cap-transform", "", ""],
    // scale
    ["", "", "cap-transform", "", ""],
    // tilt
    [
        "",
        "",
        "cap-transform",
        "affine three-corner fit (no foreshortening)",
        "",
    ],
    // smooth
    [
        "inset shadows and shadow spread keep circular corners",
        "shadows and clips keep circular corners",
        "same arc glyphs as radius",
        "",
        "",
    ],
    // grain
    [
        "",
        "",
        "cap-grain",
        "feTurbulence approximation (different noise realization)",
        "",
    ],
    // mask
    ["", "", "mask alpha sampled per cell over the box", "", ""],
    // backdrop-fade
    [
        "6-band blur approximation",
        "6-band blur approximation",
        "cap-backdrop",
        "3-band blur approximation",
        "6-band blur approximation",
    ],
    // animation
    [
        "",
        "",
        "",
        "animates paint attributes; text content and layout-affecting keyframes freeze at authored base (cap-anim-content)",
        "re-solved per frame and encoded as APNG at the requested --dur/--fps",
    ],
    // text-keyframes
    [
        "",
        "",
        "",
        "content keyframes freeze at the authored base (cap-anim-content)",
        "",
    ],
    // transition
    ["", "", "", "cap-transition", "cap-transition"],
    // themes
    ["", "", "", "", ""],
    // input
    [
        "",
        "",
        "pointer positions are quantized to character-cell centers",
        "cap-input",
        "cap-input",
    ],
    // ime
    [
        "",
        "an Esc-cancelled composition stays open until the next commit and dead-key commits arrive as plain text events",
        "cap-ime",
        "cap-ime",
        "cap-ime",
    ],
    // scroll
    ["", "", "", "cap-scroll", "cap-scroll"],
    // scroll-cross
    ["", "", "", "cap-scroll", "cap-scroll"],
    // scroll-reveal
    ["", "", "", "cap-scroll", "cap-scroll"],
    // sticky
    ["", "", "", "cap-scroll", "cap-scroll"],
    // divider
    [
        "",
        "",
        "",
        "renders authored or host-preset divider geometry; interactive resizing has no static dispatch loop",
        "renders authored or host-preset divider geometry; interactive resizing has no static dispatch loop",
    ],
    // holes
    [
        "",
        "",
        "cap-hole",
        "the hole box renders empty; a hug axis has no host report, so it uses zero before ordinary min/max clamps",
        "the hole box renders empty; a hug axis has no host report, so it uses zero before ordinary min/max clamps",
    ],
    // lists
    ["", "", "", "", ""],
    // lists-nested
    ["", "", "", "", ""],
    // para-runs
    ["", "", "", "", ""],
    // lists-virtual
    ["", "", "", "", ""],
    // popover
    ["", "", "", "", ""],
    // signals
    ["", "", "", "cap-signal", "cap-signal"],
    // a11y
    ["", "", "cap-a11y", "cap-a11y", "cap-a11y"],
    // text-edit
    [
        "",
        "cut/copy/paste do not reach the system clipboard (winit has no clipboard API)",
        "",
        "cap-edit",
        "cap-edit",
    ],
    // text-raster
    [
        "browser-rasterized glyphs; kernel line breaks and advances are authoritative",
        "",
        "wide clusters (EAW W/F, emoji presentation) occupy two cells; runs re-quantize to columns under the real font metrics",
        "viewer-rasterized glyphs; textLength force-fits each run to the kernel-measured width",
        "",
    ],
];

/// Level of `feature` on the client with kernel code `client`;
/// unknown names/codes count as FULL (nothing to report).
pub fn level(feature: &str, client: u32) -> u8 {
    let Some(f) = FEATURES.iter().position(|n| *n == feature) else {
        return FULL;
    };
    let Some(row) = LEVELS.get(f) else {
        return FULL;
    };
    *row.get(client as usize).unwrap_or(&FULL)
}

/// Note/diag-code of `feature` on `client` (`""` when full/unknown).
pub fn note(feature: &str, client: u32) -> &'static str {
    let Some(f) = FEATURES.iter().position(|n| *n == feature) else {
        return "";
    };
    let Some(row) = NOTES.get(f) else { return "" };
    row.get(client as usize).copied().unwrap_or("")
}
