[package]
name = "slab-kernel"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
png.workspace = true
rustc-hash.workspace = true
rustybuzz.workspace = true
serde.workspace = true
unicode-bidi.workspace = true
[dev-dependencies]
slab-slir.workspace = true
