import { existsSync, readFileSync, writeFileSync } from 'node:fs';

/** Writes generated bytes only when their content changed, preserving dependent build caches. */
export function writeGenerated(path: string | URL, next: Uint8Array): boolean {
   if (existsSync(path) && readFileSync(path).equals(next)) return false;
   writeFileSync(path, next);
   return true;
}
