[package]
name = "slab-compile"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
png.workspace = true
serde_json.workspace = true
slab-fonts.workspace = true
slab-kernel.workspace = true
slab-slir.workspace = true
slab-syntax.workspace = true
tiny-skia.workspace = true
ttf-parser.workspace = true
